# Desaf칤os de pr치ctica

En esta secci칩n te proponemos desaf칤os y ejercicios para pr치cticar o revisar lo que vimos en los distintos cap칤tulos. Cada una de las subsecci칩n estar치 asociada a un conjunto de cap칤tulos y buscan relacionar los distintos temas y herramientas. 

## Desaf칤o 1

**Cap칤tulos asociados:** Instalaci칩n de R y Rstudio, Uso de proyectos, Reportes con RMarkdown y lectura de datos. 

1. Segu칤 las instrucciones que encontrar치s en el [Anexo I]() para instalar R y Rstudio. Ten칠 en cuenta que la instalaci칩n en computadoras con Windows requieren algunos pasos extra. 

2. Abr칤 RStudio y cre치 tu primer proyecto. Este proyecto te acompa침ar치 a lo largo de todos los desaf칤os y ejercicios de este libro, por lo que va a necesitar un nombre f치cil de recordar. Pod칠s revisar las instrucciones [ac치](). 

3. Ahora es momento de instalar algunos paquetes para poder usar luego. Por ahora instalemos readr, remotes y datos. 

```{r eval=FALSE, include=TRUE}
install.packages("readr")
install.packages("remotes")
remotes::install_github("ciencia_datos/datos")
```

La tercera linea, si bien distinta a las anteriores, tambi칠n instala un paqute. La diferencia es que instala el paquete desde un repositorio de GitHub donde suelen estar los paquetes en desarrollo. 

4. Cre치 un nuevo archivo R Markdown que se llame "01-lectura.Rmd" desde File -> New File -> R Markdown. Si bien el archivo puede tener cualquer nombre, siempre que sea informativo, te proponemos nombrarlos como n칰mero-nombre para poder ordenarlos y que te resulte m치s f치cil encontrarlo dentro del proyecto. Borr치 la plantilla y guard치 el archivo. Para guardar File -> Save  o click en en el disquette 游. Es posible que necesites darle permiso a RStudio para que instale nuevos paquetes asociados a R Markdown. 

5. Aprovechemos el archivo recien creado para leer datos. Te proponemos que revises el cap칤tulo de [lectura de datos] y sigas las instrucciones para leer los datos. 

6. 춰Listo! En la pr칩xima secci칩n practicaremos con esos y otros datos.

## Desaf칤o 2

**Cap칤tulos asociados:** Manipulaci칩n de datos con dplyr y la primera parte de gr치ficos con ggplot2

## Desaf칤o 3

**Cap칤tulos asociados:** M치s gr치ficos con ggplot2 y manupulaci칩n de datos con dplyr y tidyr.

## Desaf칤o 4

**Cap칤tulos asociados:** Tablas, gr치ficos e informes para publicar. 