<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 4 Lectura de datos ordenados | Documento Técnico N°6: Ciencia de Datos para el Turismo</title>
  <meta name="description" content="Ciencia de Datos para el Turismo" />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 4 Lectura de datos ordenados | Documento Técnico N°6: Ciencia de Datos para el Turismo" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Ciencia de Datos para el Turismo" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 4 Lectura de datos ordenados | Documento Técnico N°6: Ciencia de Datos para el Turismo" />
  
  <meta name="twitter:description" content="Ciencia de Datos para el Turismo" />
  

<meta name="author" content="Dirección Nacional de Mercados y Estadísticas - Subsecretaría de Desarrollo Estratégico" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<<<<<<< Updated upstream
<link rel="prev" href="markdown.html"/>
<link rel="next" href="descargando-datos.html"/>
<<<<<<< HEAD
=======
=======
<link rel="prev" href="introducción-a-rmarkdown.html"/>
<link rel="next" href="manipulación-de-datos-ordenados.html"/>
>>>>>>> Stashed changes
<script src="libs/header-attrs-2.10/header-attrs.js"></script>
>>>>>>> dplyr-1
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="toc-logo"><a href="./"><img src="imagenes/escudo_mintur.png"></a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Presentación</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#documento-técnico-nº6---resumen"><i class="fa fa-check"></i>Documento Técnico Nº6 - Resumen</a></li>
</ul></li>
<<<<<<< HEAD
<li class="chapter" data-level="1" data-path="ciencia-de-datos.html"><a href="ciencia-de-datos.html"><i class="fa fa-check"></i><b>1</b> Ciencia de Datos</a><ul>
=======
<li class="chapter" data-level="1" data-path="ciencia-de-datos.html"><a href="ciencia-de-datos.html"><i class="fa fa-check"></i><b>1</b> Ciencia de Datos</a>
<ul>
<<<<<<< Updated upstream
>>>>>>> dplyr-1
<li class="chapter" data-level="1.1" data-path="por-qué-r.html"><a href="por-qué-r.html"><i class="fa fa-check"></i><b>1.1</b> ¿Por qué R?</a></li>
<li class="chapter" data-level="1.2" data-path="cómo-decirle-a-r-qué-hacer.html"><a href="cómo-decirle-a-r-qué-hacer.html"><i class="fa fa-check"></i><b>1.2</b> Cómo decirle a R qué hacer</a><ul>
<li class="chapter" data-level="1.2.1" data-path="cómo-decirle-a-r-qué-hacer.html"><a href="cómo-decirle-a-r-qué-hacer.html#orientándose-en-rstudio"><i class="fa fa-check"></i><b>1.2.1</b> Orientándose en RStudio</a></li>
<li class="chapter" data-level="1.2.2" data-path="cómo-decirle-a-r-qué-hacer.html"><a href="cómo-decirle-a-r-qué-hacer.html#hablando-con-r"><i class="fa fa-check"></i><b>1.2.2</b> Hablando con R</a></li>
<li class="chapter" data-level="1.2.3" data-path="cómo-decirle-a-r-qué-hacer.html"><a href="cómo-decirle-a-r-qué-hacer.html#extendiendo-r"><i class="fa fa-check"></i><b>1.2.3</b> Extendiendo R</a></li>
<li class="chapter" data-level="1.2.4" data-path="cómo-decirle-a-r-qué-hacer.html"><a href="cómo-decirle-a-r-qué-hacer.html#buscando-ayuda"><i class="fa fa-check"></i><b>1.2.4</b> Buscando ayuda</a></li>
=======
<li class="chapter" data-level="1.1" data-path="ciencia-de-datos.html"><a href="ciencia-de-datos.html#por-qué-r"><i class="fa fa-check"></i><b>1.1</b> ¿Por qué R?</a></li>
<li class="chapter" data-level="1.2" data-path="ciencia-de-datos.html"><a href="ciencia-de-datos.html#cómo-decirle-a-r-qué-hacer"><i class="fa fa-check"></i><b>1.2</b> Cómo decirle a R qué hacer</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="ciencia-de-datos.html"><a href="ciencia-de-datos.html#orientándose-en-rstudio"><i class="fa fa-check"></i><b>1.2.1</b> Orientándose en RStudio</a></li>
<li class="chapter" data-level="1.2.2" data-path="ciencia-de-datos.html"><a href="ciencia-de-datos.html#hablando-con-r"><i class="fa fa-check"></i><b>1.2.2</b> Hablando con R</a></li>
<li class="chapter" data-level="1.2.3" data-path="ciencia-de-datos.html"><a href="ciencia-de-datos.html#extendiendo-r"><i class="fa fa-check"></i><b>1.2.3</b> Extendiendo R</a></li>
<li class="chapter" data-level="1.2.4" data-path="ciencia-de-datos.html"><a href="ciencia-de-datos.html#buscando-ayuda"><i class="fa fa-check"></i><b>1.2.4</b> Buscando ayuda</a></li>
>>>>>>> Stashed changes
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="trabajar-con-proyectos-en-rstudio.html"><a href="trabajar-con-proyectos-en-rstudio.html"><i class="fa fa-check"></i><b>2</b> Trabajar con proyectos en RStudio</a><ul>
<li class="chapter" data-level="2.0.1" data-path="trabajar-con-proyectos-en-rstudio.html"><a href="trabajar-con-proyectos-en-rstudio.html#qué-ventajas-tiene"><i class="fa fa-check"></i><b>2.0.1</b> ¿Qué ventajas tiene?</a></li>
<li class="chapter" data-level="2.0.2" data-path="trabajar-con-proyectos-en-rstudio.html"><a href="trabajar-con-proyectos-en-rstudio.html#abrir-un-proyecto"><i class="fa fa-check"></i><b>2.0.2</b> Abrir un proyecto</a></li>
<li class="chapter" data-level="2.0.3" data-path="trabajar-con-proyectos-en-rstudio.html"><a href="trabajar-con-proyectos-en-rstudio.html#cómo-se-organiza"><i class="fa fa-check"></i><b>2.0.3</b> ¿Cómo se organiza?</a></li>
<li class="chapter" data-level="2.0.4" data-path="trabajar-con-proyectos-en-rstudio.html"><a href="trabajar-con-proyectos-en-rstudio.html#ordenando-aún-más"><i class="fa fa-check"></i><b>2.0.4</b> Ordenando aún más</a></li>
<li class="chapter" data-level="2.0.5" data-path="trabajar-con-proyectos-en-rstudio.html"><a href="trabajar-con-proyectos-en-rstudio.html#borrón-y-cuenta-nueva-todos-los-días"><i class="fa fa-check"></i><b>2.0.5</b> Borrón y cuenta nueva… todos los días!</a></li>
</ul></li>
<<<<<<< HEAD
<li class="chapter" data-level="3" data-path="introducción-a-rmarkdown.html"><a href="introducción-a-rmarkdown.html"><i class="fa fa-check"></i><b>3</b> Introducción a RMarkdown</a><ul>
=======
<<<<<<< Updated upstream
<li class="chapter" data-level="3" data-path="introducción-a-rmarkdown.html"><a href="introducción-a-rmarkdown.html"><i class="fa fa-check"></i><b>3</b> Introducción a RMarkdown</a>
<ul>
>>>>>>> dplyr-1
<li class="chapter" data-level="3.1" data-path="creando-archivos-rmd.html"><a href="creando-archivos-rmd.html"><i class="fa fa-check"></i><b>3.1</b> Creando archivos .Rmd</a></li>
<li class="chapter" data-level="3.2" data-path="estructura-de-un-rmd.html"><a href="estructura-de-un-rmd.html"><i class="fa fa-check"></i><b>3.2</b> Estructura de un .Rmd</a><ul>
<li class="chapter" data-level="3.2.1" data-path="estructura-de-un-rmd.html"><a href="estructura-de-un-rmd.html#encabezado"><i class="fa fa-check"></i><b>3.2.1</b> Encabezado</a></li>
<li class="chapter" data-level="3.2.2" data-path="estructura-de-un-rmd.html"><a href="estructura-de-un-rmd.html#bloques-de-código"><i class="fa fa-check"></i><b>3.2.2</b> Bloques de código</a></li>
<li class="chapter" data-level="3.2.3" data-path="estructura-de-un-rmd.html"><a href="estructura-de-un-rmd.html#el-texto-propio-del-documento."><i class="fa fa-check"></i><b>3.2.3</b> El texto propio del documento.</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="markdown.html"><a href="markdown.html"><i class="fa fa-check"></i><b>3.3</b> Markdown</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="lectura-de-datos-ordenados.html"><a href="lectura-de-datos-ordenados.html"><i class="fa fa-check"></i><b>4</b> Lectura de datos ordenados</a><ul>
<li class="chapter" data-level="4.1" data-path="descargando-datos.html"><a href="descargando-datos.html"><i class="fa fa-check"></i><b>4.1</b> Descargando datos</a></li>
<li class="chapter" data-level="4.2" data-path="leer-datos-csv.html"><a href="leer-datos-csv.html"><i class="fa fa-check"></i><b>4.2</b> Leer datos csv</a></li>
<li class="chapter" data-level="4.3" data-path="leer-datos-de-excel.html"><a href="leer-datos-de-excel.html"><i class="fa fa-check"></i><b>4.3</b> Leer datos de excel</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="manipulación-de-datos-ordenados.html"><a href="manipulación-de-datos-ordenados.html"><i class="fa fa-check"></i><b>5</b> Manipulación de datos ordenados</a><ul>
<li class="chapter" data-level="5.1" data-path="seleccionando-columnas-con-select.html"><a href="seleccionando-columnas-con-select.html"><i class="fa fa-check"></i><b>5.1</b> Seleccionando columnas con <code>select()</code></a></li>
<li class="chapter" data-level="5.2" data-path="filtrando-filas-con-filter.html"><a href="filtrando-filas-con-filter.html"><i class="fa fa-check"></i><b>5.2</b> Filtrando filas con <code>filter()</code></a></li>
<li class="chapter" data-level="5.3" data-path="agrupando-y-reduciendo-con-group-by-summarise.html"><a href="agrupando-y-reduciendo-con-group-by-summarise.html"><i class="fa fa-check"></i><b>5.3</b> Agrupando y reduciendo con <code>group_by() %&gt;% summarise()</code></a></li>
<li class="chapter" data-level="5.4" data-path="creando-nuevas-columnas-con-mutate.html"><a href="creando-nuevas-columnas-con-mutate.html"><i class="fa fa-check"></i><b>5.4</b> Creando nuevas columnas con <code>mutate()</code></a></li>
<li class="chapter" data-level="5.5" data-path="desagrupando-con-ungroup.html"><a href="desagrupando-con-ungroup.html"><i class="fa fa-check"></i><b>5.5</b> Desagrupando con <code>ungroup()</code></a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="gráficos-con-ggplot2.html"><a href="gráficos-con-ggplot2.html"><i class="fa fa-check"></i><b>6</b> Gráficos con ggplot2</a><ul>
<li class="chapter" data-level="6.1" data-path="primera-capa-el-área-del-gráfico.html"><a href="primera-capa-el-área-del-gráfico.html"><i class="fa fa-check"></i><b>6.1</b> Primera capa: el área del gráfico</a></li>
<li class="chapter" data-level="6.2" data-path="segunda-capa-geometrías.html"><a href="segunda-capa-geometrías.html"><i class="fa fa-check"></i><b>6.2</b> Segunda capa: geometrías</a></li>
<li class="chapter" data-level="6.3" data-path="mapear-variables-a-elementos.html"><a href="mapear-variables-a-elementos.html"><i class="fa fa-check"></i><b>6.3</b> Mapear variables a elementos</a></li>
<li class="chapter" data-level="6.4" data-path="otras-geometrías.html"><a href="otras-geometrías.html"><i class="fa fa-check"></i><b>6.4</b> Otras geometrías</a></li>
<li class="chapter" data-level="6.5" data-path="relación-entre-variables.html"><a href="relación-entre-variables.html"><i class="fa fa-check"></i><b>6.5</b> Relación entre variables</a></li>
<li class="chapter" data-level="6.6" data-path="transformaciones-estadísticas.html"><a href="transformaciones-estadísticas.html"><i class="fa fa-check"></i><b>6.6</b> Transformaciones estadísticas</a></li>
<li class="chapter" data-level="6.7" data-path="gráficos-de-frecuencias.html"><a href="gráficos-de-frecuencias.html"><i class="fa fa-check"></i><b>6.7</b> Gráficos de frecuencias</a><ul>
<li class="chapter" data-level="6.7.1" data-path="gráficos-de-frecuencias.html"><a href="gráficos-de-frecuencias.html#posición"><i class="fa fa-check"></i><b>6.7.1</b> Posición</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="gráficos-de-líneas-suavizas.html"><a href="gráficos-de-líneas-suavizas.html"><i class="fa fa-check"></i><b>6.8</b> Gráficos de líneas suavizas</a></li>
<li class="chapter" data-level="6.9" data-path="gráficos-de-caja.html"><a href="gráficos-de-caja.html"><i class="fa fa-check"></i><b>6.9</b> Gráficos de caja</a></li>
<li class="chapter" data-level="6.10" data-path="graficando-en-múltiples-paneles.html"><a href="graficando-en-múltiples-paneles.html"><i class="fa fa-check"></i><b>6.10</b> Graficando en múltiples paneles</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"><i class="fa fa-check"></i><b>7</b> Manipulación de datos ordenados usando {dplyr} y {tidyr} II</a><ul>
<li class="chapter" data-level="7.1" data-path="de-ancho-a-largo-con-pivot-longer.html"><a href="de-ancho-a-largo-con-pivot-longer.html"><i class="fa fa-check"></i><b>7.1</b> De ancho a largo con <code>pivot_longer()</code></a></li>
<li class="chapter" data-level="7.2" data-path="de-largo-a-ancho-con-pivot-wider.html"><a href="de-largo-a-ancho-con-pivot-wider.html"><i class="fa fa-check"></i><b>7.2</b> De largo a ancho con <code>pivot_wider()</code></a></li>
<li class="chapter" data-level="7.3" data-path="uniendo-tablas.html"><a href="uniendo-tablas.html"><i class="fa fa-check"></i><b>7.3</b> Uniendo tablas</a></li>
</ul></li>
<<<<<<< HEAD
<li class="chapter" data-level="8" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html"><i class="fa fa-check"></i><b>8</b> Manipulación de datos ordenados usando {dplyr} y {tidyr} II</a><ul>
<li class="chapter" data-level="8.1" data-path="de-ancho-a-largo-con-pivot-longer-1.html"><a href="de-ancho-a-largo-con-pivot-longer-1.html"><i class="fa fa-check"></i><b>8.1</b> De ancho a largo con <code>pivot_longer()</code></a></li>
<li class="chapter" data-level="8.2" data-path="de-largo-a-ancho-con-pivot-wider-1.html"><a href="de-largo-a-ancho-con-pivot-wider-1.html"><i class="fa fa-check"></i><b>8.2</b> De largo a ancho con <code>pivot_wider()</code></a></li>
<li class="chapter" data-level="8.3" data-path="uniendo-tablas-1.html"><a href="uniendo-tablas-1.html"><i class="fa fa-check"></i><b>8.3</b> Uniendo tablas</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="reportes-ii.html"><a href="reportes-ii.html"><i class="fa fa-check"></i><b>9</b> Reportes II</a><ul>
<li class="chapter" data-level="9.1" data-path="eligiendo-el-formato-de-salida.html"><a href="eligiendo-el-formato-de-salida.html"><i class="fa fa-check"></i><b>9.1</b> Eligiendo el formato de salida</a></li>
<li class="chapter" data-level="9.2" data-path="personalizando-la-salida.html"><a href="personalizando-la-salida.html"><i class="fa fa-check"></i><b>9.2</b> Personalizando la salida</a></li>
<li class="chapter" data-level="9.3" data-path="reportes-parametrizados.html"><a href="reportes-parametrizados.html"><i class="fa fa-check"></i><b>9.3</b> Reportes parametrizados</a></li>
<li class="chapter" data-level="9.4" data-path="control-de-chunks.html"><a href="control-de-chunks.html"><i class="fa fa-check"></i><b>9.4</b> Control de chunks</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="tablas.html"><a href="tablas.html"><i class="fa fa-check"></i><b>10</b> Tablas</a><ul>
<li class="chapter" data-level="10.1" data-path="tablas-simples-con-kable.html"><a href="tablas-simples-con-kable.html"><i class="fa fa-check"></i><b>10.1</b> Tablas simples con <code>kable</code></a></li>
<li class="chapter" data-level="10.2" data-path="supertablas-con-kableextra.html"><a href="supertablas-con-kableextra.html"><i class="fa fa-check"></i><b>10.2</b> Supertablas con {kableExtra}</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="apariencia-de-gráficos.html"><a href="apariencia-de-gráficos.html"><i class="fa fa-check"></i><b>11</b> Apariencia de gráficos</a><ul>
<li class="chapter" data-level="11.1" data-path="escalas.html"><a href="escalas.html"><i class="fa fa-check"></i><b>11.1</b> Escalas</a><ul>
<li class="chapter" data-level="11.1.1" data-path="escalas.html"><a href="escalas.html#escala-de-colores-y-otras"><i class="fa fa-check"></i><b>11.1.1</b> Escala de colores y otras</a></li>
<li class="chapter" data-level="11.1.2" data-path="escalas.html"><a href="escalas.html#escalas-de-ejes"><i class="fa fa-check"></i><b>11.1.2</b> Escalas de ejes</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="elementos-de-texto.html"><a href="elementos-de-texto.html"><i class="fa fa-check"></i><b>11.2</b> Elementos de texto</a></li>
<li class="chapter" data-level="11.3" data-path="temas.html"><a href="temas.html"><i class="fa fa-check"></i><b>11.3</b> Temas</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="desafíos-de-práctica.html"><a href="desafíos-de-práctica.html"><i class="fa fa-check"></i><b>12</b> Desafíos de práctica</a><ul>
<li class="chapter" data-level="12.1" data-path="desafío-1.html"><a href="desafío-1.html"><i class="fa fa-check"></i><b>12.1</b> Desafío 1</a></li>
<li class="chapter" data-level="12.2" data-path="desafío-2.html"><a href="desafío-2.html"><i class="fa fa-check"></i><b>12.2</b> Desafío 2</a></li>
<li class="chapter" data-level="12.3" data-path="desafío-3.html"><a href="desafío-3.html"><i class="fa fa-check"></i><b>12.3</b> Desafío 3</a></li>
<li class="chapter" data-level="12.4" data-path="desafío-4.html"><a href="desafío-4.html"><i class="fa fa-check"></i><b>12.4</b> Desafío 4</a></li>
=======
<li class="chapter" data-level="7.18" data-path="elementos-de-texto.html"><a href="elementos-de-texto.html"><i class="fa fa-check"></i><b>7.18</b> Elementos de texto</a></li>
<li class="chapter" data-level="7.19" data-path="temas.html"><a href="temas.html"><i class="fa fa-check"></i><b>7.19</b> Temas</a></li>
=======
<li class="chapter" data-level="3" data-path="introducción-a-rmarkdown.html"><a href="introducción-a-rmarkdown.html"><i class="fa fa-check"></i><b>3</b> Introducción a {RMarkdown}</a>
<ul>
<li class="chapter" data-level="3.0.1" data-path="introducción-a-rmarkdown.html"><a href="introducción-a-rmarkdown.html#creando-archivos-.rmd"><i class="fa fa-check"></i><b>3.0.1</b> Creando archivos .Rmd</a></li>
<li class="chapter" data-level="3.0.2" data-path="introducción-a-rmarkdown.html"><a href="introducción-a-rmarkdown.html#estructura-de-un-.rmd"><i class="fa fa-check"></i><b>3.0.2</b> Estructura de un .Rmd</a></li>
<li class="chapter" data-level="3.0.3" data-path="introducción-a-rmarkdown.html"><a href="introducción-a-rmarkdown.html#markdown"><i class="fa fa-check"></i><b>3.0.3</b> Markdown</a></li>
<li class="chapter" data-level="3.0.4" data-path="introducción-a-rmarkdown.html"><a href="introducción-a-rmarkdown.html#bloques-de-código"><i class="fa fa-check"></i><b>3.0.4</b> Bloques de código</a></li>
<li class="chapter" data-level="3.0.5" data-path="introducción-a-rmarkdown.html"><a href="introducción-a-rmarkdown.html#texto-en-línea"><i class="fa fa-check"></i><b>3.0.5</b> Texto en línea</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="lectura-de-datos-ordenados.html"><a href="lectura-de-datos-ordenados.html"><i class="fa fa-check"></i><b>4</b> Lectura de datos ordenados</a>
<ul>
<li class="chapter" data-level="4.1" data-path="lectura-de-datos-ordenados.html"><a href="lectura-de-datos-ordenados.html#descargando-datos"><i class="fa fa-check"></i><b>4.1</b> Descargando datos</a></li>
<li class="chapter" data-level="4.2" data-path="lectura-de-datos-ordenados.html"><a href="lectura-de-datos-ordenados.html#leer-datos-csv"><i class="fa fa-check"></i><b>4.2</b> Leer datos csv</a></li>
<li class="chapter" data-level="4.3" data-path="lectura-de-datos-ordenados.html"><a href="lectura-de-datos-ordenados.html#leer-datos-de-excel"><i class="fa fa-check"></i><b>4.3</b> Leer datos de excel</a></li>
<li class="chapter" data-level="4.4" data-path="lectura-de-datos-ordenados.html"><a href="lectura-de-datos-ordenados.html#formatos-de-tablas"><i class="fa fa-check"></i><b>4.4</b> Formatos de tablas</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="manipulación-de-datos-ordenados.html"><a href="manipulación-de-datos-ordenados.html"><i class="fa fa-check"></i><b>5</b> Manipulación de datos ordenados</a>
<ul>
<li class="chapter" data-level="5.1" data-path="manipulación-de-datos-ordenados.html"><a href="manipulación-de-datos-ordenados.html#seleccionando-columnas-con-select"><i class="fa fa-check"></i><b>5.1</b> Seleccionando columnas con <code>select()</code></a></li>
<li class="chapter" data-level="5.2" data-path="manipulación-de-datos-ordenados.html"><a href="manipulación-de-datos-ordenados.html#filtrando-filas-con-filter"><i class="fa fa-check"></i><b>5.2</b> Filtrando filas con <code>filter()</code></a></li>
<li class="chapter" data-level="5.3" data-path="manipulación-de-datos-ordenados.html"><a href="manipulación-de-datos-ordenados.html#agrupando-y-reduciendo-con-group_by-summarise"><i class="fa fa-check"></i><b>5.3</b> Agrupando y reduciendo con <code>group_by() %&gt;% summarise()</code></a></li>
<li class="chapter" data-level="5.4" data-path="manipulación-de-datos-ordenados.html"><a href="manipulación-de-datos-ordenados.html#creando-nuevas-columnas-con-mutate"><i class="fa fa-check"></i><b>5.4</b> Creando nuevas columnas con <code>mutate()</code></a></li>
<li class="chapter" data-level="5.5" data-path="manipulación-de-datos-ordenados.html"><a href="manipulación-de-datos-ordenados.html#desagrupando-con-ungroup"><i class="fa fa-check"></i><b>5.5</b> Desagrupando con <code>ungroup()</code></a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="gráficos-con-ggplot2.html"><a href="gráficos-con-ggplot2.html"><i class="fa fa-check"></i><b>6</b> Gráficos con ggplot2</a>
<ul>
<li class="chapter" data-level="6.1" data-path="gráficos-con-ggplot2.html"><a href="gráficos-con-ggplot2.html#primera-capa-el-área-del-gráfico"><i class="fa fa-check"></i><b>6.1</b> Primera capa: el área del gráfico</a></li>
<li class="chapter" data-level="6.2" data-path="gráficos-con-ggplot2.html"><a href="gráficos-con-ggplot2.html#segunda-capa-geometrías"><i class="fa fa-check"></i><b>6.2</b> Segunda capa: geometrías</a></li>
<li class="chapter" data-level="6.3" data-path="gráficos-con-ggplot2.html"><a href="gráficos-con-ggplot2.html#mapear-variables-a-elementos"><i class="fa fa-check"></i><b>6.3</b> Mapear variables a elementos</a></li>
<li class="chapter" data-level="6.4" data-path="gráficos-con-ggplot2.html"><a href="gráficos-con-ggplot2.html#otras-geometrías"><i class="fa fa-check"></i><b>6.4</b> Otras geometrías</a></li>
<li class="chapter" data-level="6.5" data-path="gráficos-con-ggplot2.html"><a href="gráficos-con-ggplot2.html#relación-entre-variables"><i class="fa fa-check"></i><b>6.5</b> Relación entre variables</a></li>
<li class="chapter" data-level="6.6" data-path="gráficos-con-ggplot2.html"><a href="gráficos-con-ggplot2.html#transformaciones-estadísticas"><i class="fa fa-check"></i><b>6.6</b> Transformaciones estadísticas</a></li>
<li class="chapter" data-level="6.7" data-path="gráficos-con-ggplot2.html"><a href="gráficos-con-ggplot2.html#gráficos-de-frecuencias"><i class="fa fa-check"></i><b>6.7</b> Gráficos de frecuencias</a>
<ul>
<li class="chapter" data-level="6.7.1" data-path="gráficos-con-ggplot2.html"><a href="gráficos-con-ggplot2.html#posición"><i class="fa fa-check"></i><b>6.7.1</b> Posición</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="gráficos-con-ggplot2.html"><a href="gráficos-con-ggplot2.html#gráficos-de-líneas-suavizas"><i class="fa fa-check"></i><b>6.8</b> Gráficos de líneas suavizas</a></li>
<li class="chapter" data-level="6.9" data-path="gráficos-con-ggplot2.html"><a href="gráficos-con-ggplot2.html#gráficos-de-caja"><i class="fa fa-check"></i><b>6.9</b> Gráficos de caja</a></li>
<li class="chapter" data-level="6.10" data-path="gráficos-con-ggplot2.html"><a href="gráficos-con-ggplot2.html#graficando-en-múltiples-paneles"><i class="fa fa-check"></i><b>6.10</b> Graficando en múltiples paneles</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"><i class="fa fa-check"></i><b>7</b> Manipulación de datos ordenados usando {dplyr} y {tidyr} II</a>
<ul>
<li class="chapter" data-level="7.1" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html#de-ancho-a-largo-con-pivot_longer"><i class="fa fa-check"></i><b>7.1</b> De ancho a largo con <code>pivot_longer()</code></a></li>
<li class="chapter" data-level="7.2" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html#de-largo-a-ancho-con-pivot_wider"><i class="fa fa-check"></i><b>7.2</b> De largo a ancho con <code>pivot_wider()</code></a></li>
<li class="chapter" data-level="7.3" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html#uniendo-tablas"><i class="fa fa-check"></i><b>7.3</b> Uniendo tablas</a></li>
<li class="chapter" data-level="7.4" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html#manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1"><i class="fa fa-check"></i><b>7.4</b> Manipulación de datos ordenados usando {dplyr} y {tidyr} II</a></li>
<li class="chapter" data-level="7.5" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html#de-ancho-a-largo-con-pivot_longer-1"><i class="fa fa-check"></i><b>7.5</b> De ancho a largo con <code>pivot_longer()</code></a></li>
<li class="chapter" data-level="7.6" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html#de-largo-a-ancho-con-pivot_wider-1"><i class="fa fa-check"></i><b>7.6</b> De largo a ancho con <code>pivot_wider()</code></a></li>
<li class="chapter" data-level="7.7" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html#uniendo-tablas-1"><i class="fa fa-check"></i><b>7.7</b> Uniendo tablas</a></li>
<li class="chapter" data-level="7.8" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html#reportes-ii"><i class="fa fa-check"></i><b>7.8</b> Reportes II</a></li>
<li class="chapter" data-level="7.9" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html#eligiendo-el-formato-de-salida"><i class="fa fa-check"></i><b>7.9</b> Eligiendo el formato de salida</a></li>
<li class="chapter" data-level="7.10" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html#personalizando-la-salida"><i class="fa fa-check"></i><b>7.10</b> Personalizando la salida</a></li>
<li class="chapter" data-level="7.11" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html#reportes-parametrizados"><i class="fa fa-check"></i><b>7.11</b> Reportes parametrizados</a></li>
<li class="chapter" data-level="7.12" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html#control-de-chunks"><i class="fa fa-check"></i><b>7.12</b> Control de chunks</a></li>
<li class="chapter" data-level="7.13" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html#tablas"><i class="fa fa-check"></i><b>7.13</b> Tablas</a></li>
<li class="chapter" data-level="7.14" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html#tablas-simples-con-kable"><i class="fa fa-check"></i><b>7.14</b> Tablas simples con <code>kable</code></a></li>
<li class="chapter" data-level="7.15" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html#supertablas-con-kableextra"><i class="fa fa-check"></i><b>7.15</b> Supertablas con {kableExtra}</a></li>
<li class="chapter" data-level="7.16" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html#apariencia-de-gráficos"><i class="fa fa-check"></i><b>7.16</b> Apariencia de gráficos</a></li>
<li class="chapter" data-level="7.17" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html#escalas"><i class="fa fa-check"></i><b>7.17</b> Escalas</a>
<ul>
<li class="chapter" data-level="7.17.1" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html#escala-de-colores-y-otras"><i class="fa fa-check"></i><b>7.17.1</b> Escala de colores y otras</a></li>
<li class="chapter" data-level="7.17.2" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html#escalas-de-ejes"><i class="fa fa-check"></i><b>7.17.2</b> Escalas de ejes</a></li>
</ul></li>
<li class="chapter" data-level="7.18" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html#elementos-de-texto"><i class="fa fa-check"></i><b>7.18</b> Elementos de texto</a></li>
<li class="chapter" data-level="7.19" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html#temas"><i class="fa fa-check"></i><b>7.19</b> Temas</a></li>
>>>>>>> Stashed changes
>>>>>>> dplyr-1
</ul></li>
<li class="divider"></li>
<li><b><a href="http://www.yvera.gob.ar/estadistica" target="blank">Estadísticas de Turismo</a></b></li>
<li><a href="http://datos.yvera.gob.ar/" target="blank">Datos Abiertos de Turismo</a></li>
<li><a href="https://tableros.yvera.tur.ar/" target="blank">Tableros y Reportes</a></li>
<li><a href="https://www.yvera.tur.ar/estadistica/informe" target="blank">Informes</a></li>
<li><a href="https://armonizacion.yvera.tur.ar/" target="blank">Armonización</a></li>
<li><a href="https://bitacora.yvera.tur.ar/" target="blank">Bitácora</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Documento Técnico N°6: Ciencia de Datos para el Turismo</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<link href="style.css" rel="stylesheet">
<div class="hero-image-container"> 
  <img class= "hero-image" src="imagenes/cabezal.png">
</div>
<div id="lectura-de-datos-ordenados" class="section level1">
<h1><span class="header-section-number">Capítulo 4</span> Lectura de datos ordenados</h1>
<div id="descargando-datos" class="section level2" number="4.1">
<h2><span class="header-section-number">4.1</span> Descargando datos</h2>
<p>Antes de poder leer cualquier dato en R, primero hay que encontrarlo y descargarlo.
El Ministerio de Turismo mantiene un portal de datos abierto llamado <a href="http://datos.yvera.gob.ar/">Yvera</a> donde podés buscar y descargar datos relacionados con el turismo en Argentina.</p>
<p>En esta sección vamos a descargar una serie de tiempo de los principales indicadores producidos por la Administración de Parques Nacionales.</p>
<p>Primero, navegá a <a href="http://datos.yvera.gob.ar/">http://datos.yvera.gob.ar/</a>, donde te vas a encontrar con la páigna principal de Yvera.</p>

<p><img src="imagenes/yvera-principal.png" title="Captura de pantalla de la página principal de la plataforma de datos abiertos Yvera." alt="Captura de pantalla de la página principal de la plataforma de datos abiertos Yvera." width="663" /></p>
<p>La base de datos que vamos a descargar está en el área de Turismo Naturaleza, así que hacé click en <a href="http://datos.yvera.gob.ar/dataset?groups=turismo-naturaleza">ese ícono</a> para navegar a la sección de datasets correspondiente.</p>

<p><img src="imagenes/yvera-parques.png" title="Captura de pantalla de la página principal de búsqueda de yvera, mostrando la base de datos de Parques Nacionales." alt="Captura de pantalla de la página principal de búsqueda de yvera, mostrando la base de datos de Parques Nacionales." width="663" /></p>
<p>Al momento que escribimos esta guía sólo el set de datos de Parques Nacionales es el único disponible en el tema Turismo Naturaleza.
Hacé click ahí para ir a <a href="http://datos.yvera.gob.ar/dataset/parques-nacionales">la página de este set de datos</a>.</p>

<p><img src="imagenes/yvera-parques-data.png" title="Captura de pantalla de la página con los datos relacionados con parques nacionales." alt="Captura de pantalla de la página con los datos relacionados con parques nacionales." width="663" /></p>
<p>Este set de datos tiene distintos recursos.
Varios son datos, como “Visitas a los Parques Nacionales según tipo de residencia del visitante” o “Visitas a los Parques Nacionales por región de destino según tipo de residencia del visitante”, pero también hay un recurso llamado “Ficha Técnica: Parques Nacionales”.
Este es <a href="http://datos.yvera.gob.ar/dataset/458bcbe1-855c-4bc3-a1c9-cd4e84fedbbc/resource/06e92813-b7d7-4702-8298-d73db3dbdce0/download/2021.01.05_pn.pdf">un PDF</a> con la descripción de los datos así como consideraciones metodológicas relevantes.
Es importante que si vas a usar datos siempre mires la ficha técnica para hacerte una idea de las limitaciones metodológicas que pueden tener estos datos.</p>
<p>Por ahora vamos a descargar la <a href="http://datos.yvera.gob.ar/dataset/parques-nacionales/archivo/78aea6ed-761c-4659-bdf2-7fcb0f616fad">serie de tiempo</a>.</p>

<p><img src="imagenes/yvera-parques-serie.png" title="Captura de pantalla de la página de la serie de tiempo de parques nacionales." alt="Captura de pantalla de la página de la serie de tiempo de parques nacionales." width="663" /></p>
<p>En esta pantalla te vas a encontrar con una descripción del set de datos y sus variables.
Para descargar los datos hay que hacer click en el botón que dice “<a href="http://datos.yvera.gob.ar/dataset/458bcbe1-855c-4bc3-a1c9-cd4e84fedbbc/resource/78aea6ed-761c-4659-bdf2-7fcb0f616fad/download/serie-tiempo-parques-nacionales-mensual.csv">DESCARGAR</a>”.
Guardalo en una carpeta dentro del proyecto (recomedamos organizar los datos en una carpeta llamada “datos”) y ya está listo para leer.</p>
<p>Pero si tuvieras que realizar un informe mensual sobre Parques Nacionales tendrías que hacer toda esta descarga manual cada vez que se actualiza el informe.
La gracia de usar código es automatizar todo lo más posible así que en vez de descargar manualmente el archivo, se puede descargar automáticamente desde el código de R.</p>
<p>Para eso, primero necesitás la dirección (URL) del set de datos.
Eso se consigue yendo a <a href="http://datos.yvera.gob.ar/dataset/parques-nacionales">la página del set de datos</a> y en vez de hacer click en DESCAGAR, haciendo</p>
<div class="alert alert-secondary">
<p>Click derecho → Copiar dirección del enlace</p>
</div>
<p>La URL de la serie de parques nacionales es <code>http://datos.yvera.gob.ar/dataset/458bcbe1-855c-4bc3-a1c9-cd4e84fedbbc/resource/78aea6ed-761c-4659-bdf2-7fcb0f616fad/download/serie-tiempo-parques-nacionales-mensual.csv</code>.
Guaramos eso en una variable en R</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="lectura-de-datos-ordenados.html#cb1-1" aria-hidden="true" tabindex="-1"></a>parques_url <span class="ot">&lt;-</span> <span class="st">&quot;http://datos.yvera.gob.ar/dataset/458bcbe1-855c-4bc3-a1c9-cd4e84fedbbc/resource/78aea6ed-761c-4659-bdf2-7fcb0f616fad/download/serie-tiempo-parques-nacionales-mensual.csv&quot;</span></span></code></pre></div>
<p>Y también definimos la ruta donde descargar el archivo</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="lectura-de-datos-ordenados.html#cb2-1" aria-hidden="true" tabindex="-1"></a>parques_archivo <span class="ot">&lt;-</span> <span class="st">&quot;datos/parques.csv&quot;</span></span></code></pre></div>
<p>Y finalmente usamos la función <code>download.file()</code> para descargar el archivo.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="lectura-de-datos-ordenados.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">download.file</span>(<span class="at">url =</span> parques_url, <span class="at">destfile =</span> parques_archivo)  </span></code></pre></div>
<p>Y esto va a descargar la última versión de la serie de Parques Nacionales.</p>
</div>
<div id="leer-datos-csv" class="section level2" number="4.2">
<h2><span class="header-section-number">4.2</span> Leer datos csv</h2>
<p>Existen muchas funciones distintas para leer datos dependiendo del formato en el que están guardados.
Para datos tabulares, la forma más útil es el formato csv, que es un archivo de texto plano con datos separados por coma.</p>
<p>Para importar datos hace falta escribir el código correspondiente pero también podés aprovechar el entorno gráfico de RStudio:</p>
<div class="alert alert-secondary">
<p>File → Import Dataset → From Text (readr)…</p>
</div>
<p>Esto te va abrir una ventana donde podrás elegir el archivo a importar (en este caso el archivo <code>parques.csv</code> que está dentro de la capeta <code>datos</code> del proyecto) y otros detalles.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="lectura-de-datos-ordenados.html#cb4-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">&quot;img/importar-parques.png&quot;</span>)</span></code></pre></div>
<p><img src="img/importar-parques.png" title="Diálogo de importar datos de RStudio." alt="Diálogo de importar datos de RStudio." width="641" /></p>
<p>En la pantalla principal vas a poder previsualizar los datos y ver que pinta tienen.
Abajo a la izquierda tenés varias opciones: el nombre que vas a usar para la variable (en este caso llamaremos <code>parques</code>), si la primera fila contiene los nombres de las columnas (<code>First Row as Names</code>), qué delimitador tienen los datos (en este caso <code>comma</code>, pero podría ser punto y coma u otro), etc…</p>
<p>Y abajo a la derecha es el código que vas a necesitar para efectivamente importar los datos.
Podrías apretar el botón “Import” para leer los datos pero si bien es posible, al mismo tiempo esas líneas de código no se guardan en ningún lado y entonces nuestro trabajo luego no se puede reproducir.
Por eso, te proponemos que copies ese código, cierres esa ventana con el botón “Cancel”, y pegues el código en el archivo donde estés trabajando.
Cuando lo ejecutes, se va a generar la variable <code>parques</code> con los datos.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="lectura-de-datos-ordenados.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb5-2"><a href="lectura-de-datos-ordenados.html#cb5-2" aria-hidden="true" tabindex="-1"></a>parques <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;datos/parques.csv&quot;</span>)</span></code></pre></div>
<pre><code>## Rows: 160 Columns: 22</code></pre>
<pre><code>## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr  (1): indice_tiempo
## dbl (21): residentes, no_residentes, total, buenos_aires_residentes, buenos_...</code></pre>
<pre><code>## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="alert alert-success">
<p><strong>Nota</strong>: Notá que en este caso el código para leer los datos consta de dos líneas.
La primera carga el paquete <code>readr</code> y el segundo usa la función <code>read_csv()</code> (del paquete readr) para leer el archivo .csv.
No es necesario cargar el paquete cada vez que vas a leer un archivo, pero asegurate de incluir esta línea al comienzo de tu archivo.</p>
</div>
<div class="alert alert-success">
<p><strong>Nota</strong>: La interfaz de usuario de RStudio sirve para autogenerar el código que lee el archivo.
Una vez que lo tenés, no necesitás abrirla de nuevo.</p>
</div>
<p>Todo ese texto naranja/rojo es intimidante pero no te preocupes, es sólo un mensaje que nos informa que los datos se leyeron y qué tipo de dato tiene cada columna.
Podemos explorar la estructura de la variable <code>parques</code> usando la función <code>str()</code> (de <em>structure</em> en inglés).</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="lectura-de-datos-ordenados.html#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(parques)</span></code></pre></div>
<pre><code>## spec_tbl_df [160 × 22] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
##  $ indice_tiempo             : chr [1:160] &quot;2008-01&quot; &quot;2008-02&quot; &quot;2008-03&quot; &quot;2008-04&quot; ...
##  $ residentes                : num [1:160] 352303 283145 172711 61491 48787 ...
##  $ no_residentes             : num [1:160] 198407 151809 148956 68606 43751 ...
##  $ total                     : num [1:160] 550710 434953 321667 130097 92538 ...
##  $ buenos_aires_residentes   : num [1:160] 885 624 0 462 1091 ...
##  $ buenos_aires_no_residentes: num [1:160] 0 0 0 0 0 0 0 0 0 0 ...
##  $ buenos_aires_total        : num [1:160] 885 624 0 462 1091 ...
##  $ cordoba_residentes        : num [1:160] 717 475 741 539 608 ...
##  $ cordoba_no_residentes     : num [1:160] 145 148 147 166 129 80 272 224 134 168 ...
##  $ cordoba_total             : num [1:160] 862 623 888 705 737 ...
##  $ cuyo_residentes           : num [1:160] 4965 4803 5722 1730 2299 ...
##  $ cuyo_no_residentes        : num [1:160] 179 139 178 78 103 31 131 109 76 150 ...
##  $ cuyo_total                : num [1:160] 5144 4942 5900 1808 2402 ...
##  $ litoral_residentes        : num [1:160] 111408 85853 59150 23821 28538 ...
##  $ litoral_no_residentes     : num [1:160] 55335 53596 55130 30827 29818 ...
##  $ litoral_total             : num [1:160] 166743 139449 114280 54648 58356 ...
##  $ norte_residentes          : num [1:160] 4241 5099 9204 3867 5083 ...
##  $ norte_no_residentes       : num [1:160] 774 1294 1696 728 663 ...
##  $ norte_total               : num [1:160] 5016 6393 10900 4595 5746 ...
##  $ patagonia_residentes      : num [1:160] 230087 186291 97894 31073 11169 ...
##  $ patagonia_no_residentes   : num [1:160] 141973 96632 91805 36807 13038 ...
##  $ patagonia_total           : num [1:160] 372060 282923 189699 67879 24206 ...
##  - attr(*, &quot;spec&quot;)=
##   .. cols(
##   ..   indice_tiempo = col_character(),
##   ..   residentes = col_double(),
##   ..   no_residentes = col_double(),
##   ..   total = col_double(),
##   ..   buenos_aires_residentes = col_double(),
##   ..   buenos_aires_no_residentes = col_double(),
##   ..   buenos_aires_total = col_double(),
##   ..   cordoba_residentes = col_double(),
##   ..   cordoba_no_residentes = col_double(),
##   ..   cordoba_total = col_double(),
##   ..   cuyo_residentes = col_double(),
##   ..   cuyo_no_residentes = col_double(),
##   ..   cuyo_total = col_double(),
##   ..   litoral_residentes = col_double(),
##   ..   litoral_no_residentes = col_double(),
##   ..   litoral_total = col_double(),
##   ..   norte_residentes = col_double(),
##   ..   norte_no_residentes = col_double(),
##   ..   norte_total = col_double(),
##   ..   patagonia_residentes = col_double(),
##   ..   patagonia_no_residentes = col_double(),
##   ..   patagonia_total = col_double()
##   .. )
##  - attr(*, &quot;problems&quot;)=&lt;externalptr&gt;</code></pre>
<p>Esto nos dice un montón.
La primera línea dice que es una <code>tibble</code>, que es un caso especial de la estructura de datos tabular básica de R llamada <code>data.frame</code>.
Tiene 160 filas (las <strong>observaciones</strong>) y 22 columnas (o <strong>variables</strong> que describen las observaciones).
Las siguientes líneas nos dicen los nombres de las columnas (indice_tiempo, residentes, no_residentes, etc…), su tipo de dato (<code>chr</code> o <code>num</code>), la longitud ([1:160]) y sus primeros elementos.</p>
</div>
<div id="leer-datos-de-excel" class="section level2" number="4.3">
<h2><span class="header-section-number">4.3</span> Leer datos de excel</h2>
<p>Si tenés la vista avispada, habrás notado que en el menú de “Import Dataset” hay una opción para leer datos de Excel.
En efecto, RStudio provee la misma ayuda para leer este tipo de datos:</p>
<div class="alert alert-secondary">
<p>File → Import Dataset → From Excel…</p>
</div>
<p><img src="img/importar-paises-xl.png" /></p>
<p>Notá que entre las opciones de abajo a la izquierda aparecen dos variables importantes.
Podés seleccionar de qué hoja leer los datos y qué rango usar.
Esto seguro que te va a ser muy útil para esos archivos de Excel con múltiples tablas en un archivo, o incluso múltiples tablas en cada hoja!</p>
<p>En este caso paises.xlsx es un Excel buena onda, y el código para leer los datos es muy simple:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="lectura-de-datos-ordenados.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb11-2"><a href="lectura-de-datos-ordenados.html#cb11-2" aria-hidden="true" tabindex="-1"></a>paises <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">&quot;datos/paises.xlsx&quot;</span>)</span></code></pre></div>
<p>Con la función <code>str()</code> podés confirmar que los datos leídos son los mismos que para el csv.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="lectura-de-datos-ordenados.html#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(paises)</span></code></pre></div>
<pre><code>## tibble [1,704 × 6] (S3: tbl_df/tbl/data.frame)
##  $ pais             : chr [1:1704] &quot;Afganistán&quot; &quot;Afganistán&quot; &quot;Afganistán&quot; &quot;Afganistán&quot; ...
##  $ continente       : chr [1:1704] &quot;Asia&quot; &quot;Asia&quot; &quot;Asia&quot; &quot;Asia&quot; ...
##  $ anio             : num [1:1704] 1952 1957 1962 1967 1972 ...
##  $ esperanza_de_vida: num [1:1704] 28.8 30.3 32 34 36.1 ...
##  $ poblacion        : num [1:1704] 8425333 9240934 10267083 11537966 13079460 ...
##  $ pib_per_capita   : num [1:1704] 779 821 853 836 740 ...</code></pre>
<div class="alert alert-info">
<p><strong>Desafío: Lee un archivo</strong></p>
<ol style="list-style-type: decimal">
<li>Lee el archivo <code>paises.xlsx</code>, pero solo las primeras 30 lineas</li>
<li>¿Qué cambió en código que devuelve RStudio?</li>
<li>Revisa la documentación de la función <code>read_excel()</code> para identificar otros argumentos que puedan resultarte útiles.</li>
</ol>
</div>
</div>
<div id="formatos-de-tablas" class="section level2" number="4.4">
<h2><span class="header-section-number">4.4</span> Formatos de tablas</h2>
<p>Pensá un momento en la estructura de los datos de <code>paises</code>.
Tiene seis columnas, pero sólo tres de ellas contienen valores observados (<code>esperanza_de_vida</code>, <code>poblacion</code> y <code>pib_per_capita</code>) y las otras tres son las “coordenadas”: <code>pais</code>, <code>continente</code> y <code>anio</code> son columnas que identifican la observación.
De hecho, la columna <code>pais</code> tiene un montón de datos repetidos!</p>
<p>Esto es un ejemplo de formato “largo” (o “tidy” en inglés).
La idea básica de datos “largos” es que:</p>
<ul>
<li>cada fila es una observación</li>
<li>cada columna es una variable</li>
</ul>
<p>La tabla <code>paises</code> es bastante larga (tiene 1704 filas y 6 columnas!) pero podría ser más larga aún.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="lectura-de-datos-ordenados.html#cb14-1" aria-hidden="true" tabindex="-1"></a>paises_largo <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;datos/paises_largo.csv&quot;</span>)</span>
<span id="cb14-2"><a href="lectura-de-datos-ordenados.html#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(paises_largo)</span></code></pre></div>
<pre><code>## spec_tbl_df [5,112 × 5] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
##  $ pais      : chr [1:5112] &quot;Afganistán&quot; &quot;Afganistán&quot; &quot;Afganistán&quot; &quot;Afganistán&quot; ...
##  $ continente: chr [1:5112] &quot;Asia&quot; &quot;Asia&quot; &quot;Asia&quot; &quot;Asia&quot; ...
##  $ anio      : num [1:5112] 1952 1957 1962 1967 1972 ...
##  $ variable  : chr [1:5112] &quot;esperanza_de_vida&quot; &quot;esperanza_de_vida&quot; &quot;esperanza_de_vida&quot; &quot;esperanza_de_vida&quot; ...
##  $ valor     : num [1:5112] 28.8 30.3 32 34 36.1 ...
##  - attr(*, &quot;spec&quot;)=
##   .. cols(
##   ..   pais = col_character(),
##   ..   continente = col_character(),
##   ..   anio = col_double(),
##   ..   variable = col_character(),
##   ..   valor = col_double()
##   .. )
##  - attr(*, &quot;problems&quot;)=&lt;externalptr&gt;</code></pre>
<p>La tabla <code>paises_largo</code> tiene ¡5112 filas!
Tiene un valor para cada país, año y variable.
Es decir, las tres columnas que contenían valores numéricos (<code>esperanza_de_vida</code>, <code>poblacion</code> y <code>pib_per_capita</code>), en esta tabla son una sola columna llamada “valor”.</p>
<p>Pero también pueden ser podría ser más “ancha”:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="lectura-de-datos-ordenados.html#cb16-1" aria-hidden="true" tabindex="-1"></a>paises_ancho <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;datos/paises_ancho.csv&quot;</span>)</span>
<span id="cb16-2"><a href="lectura-de-datos-ordenados.html#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(paises_ancho)</span></code></pre></div>
<pre><code>## spec_tbl_df [142 × 38] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
##  $ continente            : chr [1:142] &quot;Africa&quot; &quot;Africa&quot; &quot;Africa&quot; &quot;Africa&quot; ...
##  $ pais                  : chr [1:142] &quot;Algeria&quot; &quot;Angola&quot; &quot;Benin&quot; &quot;Botswana&quot; ...
##  $ pib_per_capita_1952   : num [1:142] 2449 3521 1063 851 543 ...
##  $ pib_per_capita_1957   : num [1:142] 3014 3828 960 918 617 ...
##  $ pib_per_capita_1962   : num [1:142] 2551 4269 949 984 723 ...
##  $ pib_per_capita_1967   : num [1:142] 3247 5523 1036 1215 795 ...
##  $ pib_per_capita_1972   : num [1:142] 4183 5473 1086 2264 855 ...
##  $ pib_per_capita_1977   : num [1:142] 4910 3009 1029 3215 743 ...
##  $ pib_per_capita_1982   : num [1:142] 5745 2757 1278 4551 807 ...
##  $ pib_per_capita_1987   : num [1:142] 5681 2430 1226 6206 912 ...
##  $ pib_per_capita_1992   : num [1:142] 5023 2628 1191 7954 932 ...
##  $ pib_per_capita_1997   : num [1:142] 4797 2277 1233 8647 946 ...
##  $ pib_per_capita_2002   : num [1:142] 5288 2773 1373 11004 1038 ...
##  $ pib_per_capita_2007   : num [1:142] 6223 4797 1441 12570 1217 ...
##  $ esperanza_de_vida_1952: num [1:142] 43.1 30 38.2 47.6 32 ...
##  $ esperanza_de_vida_1957: num [1:142] 45.7 32 40.4 49.6 34.9 ...
##  $ esperanza_de_vida_1962: num [1:142] 48.3 34 42.6 51.5 37.8 ...
##  $ esperanza_de_vida_1967: num [1:142] 51.4 36 44.9 53.3 40.7 ...
##  $ esperanza_de_vida_1972: num [1:142] 54.5 37.9 47 56 43.6 ...
##  $ esperanza_de_vida_1977: num [1:142] 58 39.5 49.2 59.3 46.1 ...
##  $ esperanza_de_vida_1982: num [1:142] 61.4 39.9 50.9 61.5 48.1 ...
##  $ esperanza_de_vida_1987: num [1:142] 65.8 39.9 52.3 63.6 49.6 ...
##  $ esperanza_de_vida_1992: num [1:142] 67.7 40.6 53.9 62.7 50.3 ...
##  $ esperanza_de_vida_1997: num [1:142] 69.2 41 54.8 52.6 50.3 ...
##  $ esperanza_de_vida_2002: num [1:142] 71 41 54.4 46.6 50.6 ...
##  $ esperanza_de_vida_2007: num [1:142] 72.3 42.7 56.7 50.7 52.3 ...
##  $ poblacion_1952        : num [1:142] 9279525 4232095 1738315 442308 4469979 ...
##  $ poblacion_1957        : num [1:142] 10270856 4561361 1925173 474639 4713416 ...
##  $ poblacion_1962        : num [1:142] 11000948 4826015 2151895 512764 4919632 ...
##  $ poblacion_1967        : num [1:142] 12760499 5247469 2427334 553541 5127935 ...
##  $ poblacion_1972        : num [1:142] 14760787 5894858 2761407 619351 5433886 ...
##  $ poblacion_1977        : num [1:142] 17152804 6162675 3168267 781472 5889574 ...
##  $ poblacion_1982        : num [1:142] 20033753 7016384 3641603 970347 6634596 ...
##  $ poblacion_1987        : num [1:142] 23254956 7874230 4243788 1151184 7586551 ...
##  $ poblacion_1992        : num [1:142] 26298373 8735988 4981671 1342614 8878303 ...
##  $ poblacion_1997        : num [1:142] 29072015 9875024 6066080 1536536 10352843 ...
##  $ poblacion_2002        : num [1:142] 31287142 10866106 7026113 1630347 12251209 ...
##  $ poblacion_2007        : num [1:142] 33333216 12420476 8078314 1639131 14326203 ...
##  - attr(*, &quot;spec&quot;)=
##   .. cols(
##   ..   continente = col_character(),
##   ..   pais = col_character(),
##   ..   pib_per_capita_1952 = col_double(),
##   ..   pib_per_capita_1957 = col_double(),
##   ..   pib_per_capita_1962 = col_double(),
##   ..   pib_per_capita_1967 = col_double(),
##   ..   pib_per_capita_1972 = col_double(),
##   ..   pib_per_capita_1977 = col_double(),
##   ..   pib_per_capita_1982 = col_double(),
##   ..   pib_per_capita_1987 = col_double(),
##   ..   pib_per_capita_1992 = col_double(),
##   ..   pib_per_capita_1997 = col_double(),
##   ..   pib_per_capita_2002 = col_double(),
##   ..   pib_per_capita_2007 = col_double(),
##   ..   esperanza_de_vida_1952 = col_double(),
##   ..   esperanza_de_vida_1957 = col_double(),
##   ..   esperanza_de_vida_1962 = col_double(),
##   ..   esperanza_de_vida_1967 = col_double(),
##   ..   esperanza_de_vida_1972 = col_double(),
##   ..   esperanza_de_vida_1977 = col_double(),
##   ..   esperanza_de_vida_1982 = col_double(),
##   ..   esperanza_de_vida_1987 = col_double(),
##   ..   esperanza_de_vida_1992 = col_double(),
##   ..   esperanza_de_vida_1997 = col_double(),
##   ..   esperanza_de_vida_2002 = col_double(),
##   ..   esperanza_de_vida_2007 = col_double(),
##   ..   poblacion_1952 = col_double(),
##   ..   poblacion_1957 = col_double(),
##   ..   poblacion_1962 = col_double(),
##   ..   poblacion_1967 = col_double(),
##   ..   poblacion_1972 = col_double(),
##   ..   poblacion_1977 = col_double(),
##   ..   poblacion_1982 = col_double(),
##   ..   poblacion_1987 = col_double(),
##   ..   poblacion_1992 = col_double(),
##   ..   poblacion_1997 = col_double(),
##   ..   poblacion_2002 = col_double(),
##   ..   poblacion_2007 = col_double()
##   .. )
##  - attr(*, &quot;problems&quot;)=&lt;externalptr&gt;</code></pre>
<p><code>paises_ancho</code> tiene una sola fila para cada país, y los datos de cada variable y año está en una columna propia.</p>
<p>Ninguna estructura de datos es “la correcta”; distintos análisis y distintas funciones se llevan mejor con los datos en distinto “grado de longitud”.
Es muy normal empezar con datos largos, tener que pasarlos a anchos para hacer un análisis y luego volver a pasar a largos (tan normal que hay <a href="https://github.com/dgrtwo/widyr">un paquete de R que encapsula ese proceso</a>).</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<<<<<<< Updated upstream
<a href="markdown.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="descargando-datos.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
=======
<a href="introducción-a-rmarkdown.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="manipulación-de-datos-ordenados.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
>>>>>>> Stashed changes
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["DT6.pdf", "DT6.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
