<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
<<<<<<< HEAD
=======
<<<<<<< Updated upstream
<<<<<<< Updated upstream
<<<<<<< HEAD
>>>>>>> ggplot2
  <title>Capítulo 8 Manipulación de datos ordenados usando {dplyr} y {tidyr} II | Documento Técnico N°6: Ciencia de Datos para el Turismo</title>
  <meta name="description" content="Ciencia de Datos para el Turismo" />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 8 Manipulación de datos ordenados usando {dplyr} y {tidyr} II | Documento Técnico N°6: Ciencia de Datos para el Turismo" />
<<<<<<< HEAD
=======
=======
  <title>7.4 Manipulación de datos ordenados usando {dplyr} y {tidyr} II | Documento Técnico N°6: Ciencia de Datos para el Turismo</title>
  <meta name="description" content="Ciencia de Datos para el Turismo" />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="7.4 Manipulación de datos ordenados usando {dplyr} y {tidyr} II | Documento Técnico N°6: Ciencia de Datos para el Turismo" />
>>>>>>> dplyr-1
=======
=======
>>>>>>> Stashed changes
  <title>Capítulo 7 Manipulación de datos ordenados usando {dplyr} y {tidyr} II | Documento Técnico N°6: Ciencia de Datos para el Turismo</title>
  <meta name="description" content="Ciencia de Datos para el Turismo" />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 7 Manipulación de datos ordenados usando {dplyr} y {tidyr} II | Documento Técnico N°6: Ciencia de Datos para el Turismo" />
<<<<<<< Updated upstream
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
>>>>>>> ggplot2
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Ciencia de Datos para el Turismo" />
  

  <meta name="twitter:card" content="summary" />
<<<<<<< HEAD
  <meta name="twitter:title" content="Capítulo 8 Manipulación de datos ordenados usando {dplyr} y {tidyr} II | Documento Técnico N°6: Ciencia de Datos para el Turismo" />
=======
<<<<<<< Updated upstream
<<<<<<< Updated upstream
<<<<<<< HEAD
  <meta name="twitter:title" content="Capítulo 8 Manipulación de datos ordenados usando {dplyr} y {tidyr} II | Documento Técnico N°6: Ciencia de Datos para el Turismo" />
=======
  <meta name="twitter:title" content="7.4 Manipulación de datos ordenados usando {dplyr} y {tidyr} II | Documento Técnico N°6: Ciencia de Datos para el Turismo" />
>>>>>>> dplyr-1
=======
  <meta name="twitter:title" content="Capítulo 7 Manipulación de datos ordenados usando {dplyr} y {tidyr} II | Documento Técnico N°6: Ciencia de Datos para el Turismo" />
>>>>>>> Stashed changes
=======
  <meta name="twitter:title" content="Capítulo 7 Manipulación de datos ordenados usando {dplyr} y {tidyr} II | Documento Técnico N°6: Ciencia de Datos para el Turismo" />
>>>>>>> Stashed changes
>>>>>>> ggplot2
  
  <meta name="twitter:description" content="Ciencia de Datos para el Turismo" />
  

<meta name="author" content="Dirección Nacional de Mercados y Estadísticas - Subsecretaría de Desarrollo Estratégico" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<<<<<<< HEAD
<link rel="prev" href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"/>
<link rel="next" href="reportes-ii.html"/>
<script src="libs/header-attrs-2.10/header-attrs.js"></script>
=======
<<<<<<< Updated upstream
<<<<<<< Updated upstream
<link rel="prev" href="uniendo-tablas.html"/>
<link rel="next" href="de-ancho-a-largo-con-pivot-longer-1.html"/>
<<<<<<< HEAD
=======
<script src="libs/header-attrs-2.10/header-attrs.js"></script>
>>>>>>> dplyr-1
=======
<link rel="prev" href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"/>
<link rel="next" href="reportes-ii.html"/>
<script src="libs/header-attrs-2.10/header-attrs.js"></script>
>>>>>>> Stashed changes
=======
<link rel="prev" href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"/>
<link rel="next" href="reportes-ii.html"/>
<script src="libs/header-attrs-2.10/header-attrs.js"></script>
>>>>>>> Stashed changes
>>>>>>> ggplot2
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<<<<<<< HEAD
=======
<<<<<<< Updated upstream
<<<<<<< Updated upstream
<<<<<<< HEAD
<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
=======
>>>>>>> dplyr-1
=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
>>>>>>> ggplot2
<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
<<<<<<< HEAD
=======
<<<<<<< Updated upstream
<<<<<<< Updated upstream
<<<<<<< HEAD
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
=======
=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
>>>>>>> ggplot2
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
<<<<<<< HEAD
=======
<<<<<<< Updated upstream
<<<<<<< Updated upstream
>>>>>>> dplyr-1
=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
>>>>>>> ggplot2
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
<<<<<<< HEAD
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
=======
<<<<<<< Updated upstream
<<<<<<< Updated upstream
<<<<<<< HEAD
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
=======
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
>>>>>>> dplyr-1
=======
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
>>>>>>> Stashed changes
=======
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
>>>>>>> Stashed changes
>>>>>>> ggplot2
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
<<<<<<< HEAD
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
=======
<<<<<<< Updated upstream
<<<<<<< Updated upstream
<<<<<<< HEAD
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
=======
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
>>>>>>> dplyr-1
=======
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
>>>>>>> Stashed changes
=======
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
>>>>>>> Stashed changes
>>>>>>> ggplot2
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="toc-logo"><a href="./"><img src="imagenes/escudo_mintur.png"></a></li>

<li class="divider"></li>
<<<<<<< HEAD
=======
<<<<<<< Updated upstream
<<<<<<< Updated upstream
<<<<<<< HEAD
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Presentación</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#documento-técnico-nº6---resumen"><i class="fa fa-check"></i>Documento Técnico Nº6 - Resumen</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="ciencia-de-datos.html"><a href="ciencia-de-datos.html"><i class="fa fa-check"></i><b>1</b> Ciencia de Datos</a><ul>
<li class="chapter" data-level="1.1" data-path="por-qué-r.html"><a href="por-qué-r.html"><i class="fa fa-check"></i><b>1.1</b> ¿Por qué R?</a></li>
<li class="chapter" data-level="1.2" data-path="cómo-decirle-a-r-qué-hacer.html"><a href="cómo-decirle-a-r-qué-hacer.html"><i class="fa fa-check"></i><b>1.2</b> Cómo decirle a R qué hacer</a><ul>
=======
=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
>>>>>>> ggplot2
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Presentación</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#documento-técnico-nº6---resumen"><i class="fa fa-check"></i>Documento Técnico Nº6 - Resumen</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="ciencia-de-datos.html"><a href="ciencia-de-datos.html"><i class="fa fa-check"></i><b>1</b> Ciencia de Datos</a>
<ul>
<<<<<<< HEAD
<li class="chapter" data-level="1.1" data-path="ciencia-de-datos.html"><a href="ciencia-de-datos.html#por-qué-r"><i class="fa fa-check"></i><b>1.1</b> ¿Por qué R?</a></li>
<li class="chapter" data-level="1.2" data-path="ciencia-de-datos.html"><a href="ciencia-de-datos.html#cómo-decirle-a-r-qué-hacer"><i class="fa fa-check"></i><b>1.2</b> Cómo decirle a R qué hacer</a>
=======
<<<<<<< Updated upstream
<<<<<<< Updated upstream
<li class="chapter" data-level="1.1" data-path="por-qué-r.html"><a href="por-qué-r.html"><i class="fa fa-check"></i><b>1.1</b> ¿Por qué R?</a></li>
<li class="chapter" data-level="1.2" data-path="cómo-decirle-a-r-qué-hacer.html"><a href="cómo-decirle-a-r-qué-hacer.html"><i class="fa fa-check"></i><b>1.2</b> Cómo decirle a R qué hacer</a>
>>>>>>> ggplot2
<ul>
<li class="chapter" data-level="1.2.1" data-path="ciencia-de-datos.html"><a href="ciencia-de-datos.html#orientándose-en-rstudio"><i class="fa fa-check"></i><b>1.2.1</b> Orientándose en RStudio</a></li>
<li class="chapter" data-level="1.2.2" data-path="ciencia-de-datos.html"><a href="ciencia-de-datos.html#hablando-con-r"><i class="fa fa-check"></i><b>1.2.2</b> Hablando con R</a></li>
<li class="chapter" data-level="1.2.3" data-path="ciencia-de-datos.html"><a href="ciencia-de-datos.html#extendiendo-r"><i class="fa fa-check"></i><b>1.2.3</b> Extendiendo R</a></li>
<li class="chapter" data-level="1.2.4" data-path="ciencia-de-datos.html"><a href="ciencia-de-datos.html#buscando-ayuda"><i class="fa fa-check"></i><b>1.2.4</b> Buscando ayuda</a></li>
</ul></li>
</ul></li>
<<<<<<< HEAD
=======
<<<<<<< HEAD
<li class="chapter" data-level="2" data-path="trabajar-con-proyectos-en-rstudio.html"><a href="trabajar-con-proyectos-en-rstudio.html"><i class="fa fa-check"></i><b>2</b> Trabajar con proyectos en RStudio</a><ul>
=======
=======
>>>>>>> Stashed changes
<li class="chapter" data-level="1.1" data-path="ciencia-de-datos.html"><a href="ciencia-de-datos.html#por-qué-r"><i class="fa fa-check"></i><b>1.1</b> ¿Por qué R?</a></li>
<li class="chapter" data-level="1.2" data-path="ciencia-de-datos.html"><a href="ciencia-de-datos.html#cómo-decirle-a-r-qué-hacer"><i class="fa fa-check"></i><b>1.2</b> Cómo decirle a R qué hacer</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="ciencia-de-datos.html"><a href="ciencia-de-datos.html#orientándose-en-rstudio"><i class="fa fa-check"></i><b>1.2.1</b> Orientándose en RStudio</a></li>
<li class="chapter" data-level="1.2.2" data-path="ciencia-de-datos.html"><a href="ciencia-de-datos.html#hablando-con-r"><i class="fa fa-check"></i><b>1.2.2</b> Hablando con R</a></li>
<li class="chapter" data-level="1.2.3" data-path="ciencia-de-datos.html"><a href="ciencia-de-datos.html#extendiendo-r"><i class="fa fa-check"></i><b>1.2.3</b> Extendiendo R</a></li>
<li class="chapter" data-level="1.2.4" data-path="ciencia-de-datos.html"><a href="ciencia-de-datos.html#buscando-ayuda"><i class="fa fa-check"></i><b>1.2.4</b> Buscando ayuda</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="trabajar-con-proyectos-en-rstudio.html"><a href="trabajar-con-proyectos-en-rstudio.html"><i class="fa fa-check"></i><b>2</b> Trabajar con proyectos en RStudio</a>
<ul>
<<<<<<< Updated upstream
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
<li class="chapter" data-level="2.0.1" data-path="trabajar-con-proyectos-en-rstudio.html"><a href="trabajar-con-proyectos-en-rstudio.html#qué-ventajas-tiene"><i class="fa fa-check"></i><b>2.0.1</b> ¿Qué ventajas tiene?</a></li>
<li class="chapter" data-level="2.0.2" data-path="trabajar-con-proyectos-en-rstudio.html"><a href="trabajar-con-proyectos-en-rstudio.html#abrir-un-proyecto"><i class="fa fa-check"></i><b>2.0.2</b> Abrir un proyecto</a></li>
<li class="chapter" data-level="2.0.3" data-path="trabajar-con-proyectos-en-rstudio.html"><a href="trabajar-con-proyectos-en-rstudio.html#cómo-se-organiza"><i class="fa fa-check"></i><b>2.0.3</b> ¿Cómo se organiza?</a></li>
<li class="chapter" data-level="2.0.4" data-path="trabajar-con-proyectos-en-rstudio.html"><a href="trabajar-con-proyectos-en-rstudio.html#ordenando-aún-más"><i class="fa fa-check"></i><b>2.0.4</b> Ordenando aún más</a></li>
<li class="chapter" data-level="2.0.5" data-path="trabajar-con-proyectos-en-rstudio.html"><a href="trabajar-con-proyectos-en-rstudio.html#borrón-y-cuenta-nueva-todos-los-días"><i class="fa fa-check"></i><b>2.0.5</b> Borrón y cuenta nueva… todos los días!</a></li>
</ul></li>
<<<<<<< Updated upstream
<<<<<<< Updated upstream
<li class="chapter" data-level="3" data-path="introducción-a-rmarkdown.html"><a href="introducción-a-rmarkdown.html"><i class="fa fa-check"></i><b>3</b> Introducción a RMarkdown</a><ul>
<li class="chapter" data-level="3.1" data-path="creando-archivos-rmd.html"><a href="creando-archivos-rmd.html"><i class="fa fa-check"></i><b>3.1</b> Creando archivos .Rmd</a></li>
<li class="chapter" data-level="3.2" data-path="estructura-de-un-rmd.html"><a href="estructura-de-un-rmd.html"><i class="fa fa-check"></i><b>3.2</b> Estructura de un .Rmd</a><ul>
<li class="chapter" data-level="3.2.1" data-path="estructura-de-un-rmd.html"><a href="estructura-de-un-rmd.html#encabezado"><i class="fa fa-check"></i><b>3.2.1</b> Encabezado</a></li>
<li class="chapter" data-level="3.2.2" data-path="estructura-de-un-rmd.html"><a href="estructura-de-un-rmd.html#bloques-de-código"><i class="fa fa-check"></i><b>3.2.2</b> Bloques de código</a></li>
<li class="chapter" data-level="3.2.3" data-path="estructura-de-un-rmd.html"><a href="estructura-de-un-rmd.html#el-texto-propio-del-documento."><i class="fa fa-check"></i><b>3.2.3</b> El texto propio del documento.</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="markdown.html"><a href="markdown.html"><i class="fa fa-check"></i><b>3.3</b> Markdown</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="lectura-de-datos-ordenados.html"><a href="lectura-de-datos-ordenados.html"><i class="fa fa-check"></i><b>4</b> Lectura de datos ordenados</a><ul>
<li class="chapter" data-level="4.1" data-path="descargando-datos.html"><a href="descargando-datos.html"><i class="fa fa-check"></i><b>4.1</b> Descargando datos</a></li>
<li class="chapter" data-level="4.2" data-path="leer-datos-csv.html"><a href="leer-datos-csv.html"><i class="fa fa-check"></i><b>4.2</b> Leer datos csv</a></li>
<li class="chapter" data-level="4.3" data-path="leer-datos-de-excel.html"><a href="leer-datos-de-excel.html"><i class="fa fa-check"></i><b>4.3</b> Leer datos de excel</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="manipulación-de-datos-ordenados.html"><a href="manipulación-de-datos-ordenados.html"><i class="fa fa-check"></i><b>5</b> Manipulación de datos ordenados</a><ul>
=======
>>>>>>> ggplot2
<li class="chapter" data-level="2" data-path="trabajar-con-proyectos-en-rstudio.html"><a href="trabajar-con-proyectos-en-rstudio.html"><i class="fa fa-check"></i><b>2</b> Trabajar con proyectos en RStudio</a>
<ul>
<li class="chapter" data-level="2.1" data-path="trabajar-con-proyectos-en-rstudio.html"><a href="trabajar-con-proyectos-en-rstudio.html#qué-ventajas-tiene"><i class="fa fa-check"></i><b>2.1</b> ¿Qué ventajas tiene?</a></li>
<li class="chapter" data-level="2.2" data-path="trabajar-con-proyectos-en-rstudio.html"><a href="trabajar-con-proyectos-en-rstudio.html#abrir-un-proyecto"><i class="fa fa-check"></i><b>2.2</b> Abrir un proyecto</a></li>
<li class="chapter" data-level="2.3" data-path="trabajar-con-proyectos-en-rstudio.html"><a href="trabajar-con-proyectos-en-rstudio.html#cómo-se-organiza"><i class="fa fa-check"></i><b>2.3</b> ¿Cómo se organiza?</a></li>
<li class="chapter" data-level="2.4" data-path="trabajar-con-proyectos-en-rstudio.html"><a href="trabajar-con-proyectos-en-rstudio.html#ordenando-aún-más"><i class="fa fa-check"></i><b>2.4</b> Ordenando aún más</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="trabajar-con-proyectos-en-rstudio.html"><a href="trabajar-con-proyectos-en-rstudio.html#borrón-y-cuenta-nueva-todos-los-días"><i class="fa fa-check"></i><b>2.4.1</b> Borrón y cuenta nueva… todos los días!</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="introducción-a-rmarkdown.html"><a href="introducción-a-rmarkdown.html"><i class="fa fa-check"></i><b>3</b> Introducción a RMarkdown</a>
<ul>
<li class="chapter" data-level="3.1" data-path="introducción-a-rmarkdown.html"><a href="introducción-a-rmarkdown.html#creando-archivos-.rmd"><i class="fa fa-check"></i><b>3.1</b> Creando archivos .Rmd</a></li>
<li class="chapter" data-level="3.2" data-path="introducción-a-rmarkdown.html"><a href="introducción-a-rmarkdown.html#estructura-de-un-.rmd"><i class="fa fa-check"></i><b>3.2</b> Estructura de un .Rmd</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="introducción-a-rmarkdown.html"><a href="introducción-a-rmarkdown.html#encabezado"><i class="fa fa-check"></i><b>3.2.1</b> Encabezado</a></li>
<li class="chapter" data-level="3.2.2" data-path="introducción-a-rmarkdown.html"><a href="introducción-a-rmarkdown.html#bloques-de-código"><i class="fa fa-check"></i><b>3.2.2</b> Bloques de código</a></li>
<li class="chapter" data-level="3.2.3" data-path="introducción-a-rmarkdown.html"><a href="introducción-a-rmarkdown.html#el-texto-propio-del-documento."><i class="fa fa-check"></i><b>3.2.3</b> El texto propio del documento.</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="introducción-a-rmarkdown.html"><a href="introducción-a-rmarkdown.html#markdown"><i class="fa fa-check"></i><b>3.3</b> Markdown</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="lectura-de-datos-ordenados.html"><a href="lectura-de-datos-ordenados.html"><i class="fa fa-check"></i><b>4</b> Lectura de datos ordenados</a>
<ul>
<li class="chapter" data-level="4.1" data-path="lectura-de-datos-ordenados.html"><a href="lectura-de-datos-ordenados.html#descargando-datos"><i class="fa fa-check"></i><b>4.1</b> Descargando datos</a></li>
<li class="chapter" data-level="4.2" data-path="lectura-de-datos-ordenados.html"><a href="lectura-de-datos-ordenados.html#leer-datos-csv"><i class="fa fa-check"></i><b>4.2</b> Leer datos csv</a></li>
<li class="chapter" data-level="4.3" data-path="lectura-de-datos-ordenados.html"><a href="lectura-de-datos-ordenados.html#leer-datos-de-excel"><i class="fa fa-check"></i><b>4.3</b> Leer datos de excel</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="manipulación-de-datos-ordenados.html"><a href="manipulación-de-datos-ordenados.html"><i class="fa fa-check"></i><b>5</b> Manipulación de datos ordenados</a>
<ul>
<li class="chapter" data-level="5.1" data-path="manipulación-de-datos-ordenados.html"><a href="manipulación-de-datos-ordenados.html#seleccionando-columnas-con-select"><i class="fa fa-check"></i><b>5.1</b> Seleccionando columnas con <code>select()</code></a></li>
<li class="chapter" data-level="5.2" data-path="manipulación-de-datos-ordenados.html"><a href="manipulación-de-datos-ordenados.html#filtrando-filas-con-filter"><i class="fa fa-check"></i><b>5.2</b> Filtrando filas con <code>filter()</code></a></li>
<li class="chapter" data-level="5.3" data-path="manipulación-de-datos-ordenados.html"><a href="manipulación-de-datos-ordenados.html#agrupando-y-reduciendo-con-group_by-summarise"><i class="fa fa-check"></i><b>5.3</b> Agrupando y reduciendo con <code>group_by() %&gt;% summarise()</code></a></li>
<li class="chapter" data-level="5.4" data-path="manipulación-de-datos-ordenados.html"><a href="manipulación-de-datos-ordenados.html#creando-nuevas-columnas-con-mutate"><i class="fa fa-check"></i><b>5.4</b> Creando nuevas columnas con <code>mutate()</code></a></li>
<li class="chapter" data-level="5.5" data-path="manipulación-de-datos-ordenados.html"><a href="manipulación-de-datos-ordenados.html#desagrupando-con-ungroup"><i class="fa fa-check"></i><b>5.5</b> Desagrupando con <code>ungroup()</code></a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="gráficos-con-ggplot2.html"><a href="gráficos-con-ggplot2.html"><i class="fa fa-check"></i><b>6</b> Gráficos con ggplot2</a>
<ul>
<li class="chapter" data-level="6.1" data-path="gráficos-con-ggplot2.html"><a href="gráficos-con-ggplot2.html#primera-capa-el-área-del-gráfico"><i class="fa fa-check"></i><b>6.1</b> Primera capa: el área del gráfico</a></li>
<li class="chapter" data-level="6.2" data-path="gráficos-con-ggplot2.html"><a href="gráficos-con-ggplot2.html#segunda-capa-geometrías"><i class="fa fa-check"></i><b>6.2</b> Segunda capa: geometrías</a></li>
<li class="chapter" data-level="6.3" data-path="gráficos-con-ggplot2.html"><a href="gráficos-con-ggplot2.html#mapear-variables-a-elementos"><i class="fa fa-check"></i><b>6.3</b> Mapear variables a elementos</a></li>
<li class="chapter" data-level="6.4" data-path="gráficos-con-ggplot2.html"><a href="gráficos-con-ggplot2.html#otras-geometrías"><i class="fa fa-check"></i><b>6.4</b> Otras geometrías</a></li>
<li class="chapter" data-level="6.5" data-path="gráficos-con-ggplot2.html"><a href="gráficos-con-ggplot2.html#relación-entre-variables"><i class="fa fa-check"></i><b>6.5</b> Relación entre variables</a></li>
<li class="chapter" data-level="6.6" data-path="gráficos-con-ggplot2.html"><a href="gráficos-con-ggplot2.html#transformaciones-estadísticas"><i class="fa fa-check"></i><b>6.6</b> Transformaciones estadísticas</a></li>
<li class="chapter" data-level="6.7" data-path="gráficos-con-ggplot2.html"><a href="gráficos-con-ggplot2.html#gráficos-de-frecuencias"><i class="fa fa-check"></i><b>6.7</b> Gráficos de frecuencias</a>
<ul>
<li class="chapter" data-level="6.7.1" data-path="gráficos-con-ggplot2.html"><a href="gráficos-con-ggplot2.html#posición"><i class="fa fa-check"></i><b>6.7.1</b> Posición</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="gráficos-con-ggplot2.html"><a href="gráficos-con-ggplot2.html#gráficos-de-líneas-suavizas"><i class="fa fa-check"></i><b>6.8</b> Gráficos de líneas suavizas</a></li>
<li class="chapter" data-level="6.9" data-path="gráficos-con-ggplot2.html"><a href="gráficos-con-ggplot2.html#gráficos-de-caja"><i class="fa fa-check"></i><b>6.9</b> Gráficos de caja</a></li>
<li class="chapter" data-level="6.10" data-path="gráficos-con-ggplot2.html"><a href="gráficos-con-ggplot2.html#graficando-en-múltiples-paneles"><i class="fa fa-check"></i><b>6.10</b> Graficando en múltiples paneles</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"><i class="fa fa-check"></i><b>7</b> Manipulación de datos ordenados usando {dplyr} y {tidyr} II</a>
<ul>
<li class="chapter" data-level="7.1" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html#de-ancho-a-largo-con-pivot_longer"><i class="fa fa-check"></i><b>7.1</b> De ancho a largo con <code>pivot_longer()</code></a></li>
<li class="chapter" data-level="7.2" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html#de-largo-a-ancho-con-pivot_wider"><i class="fa fa-check"></i><b>7.2</b> De largo a ancho con <code>pivot_wider()</code></a></li>
<li class="chapter" data-level="7.3" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html#uniendo-tablas"><i class="fa fa-check"></i><b>7.3</b> Uniendo tablas</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html"><i class="fa fa-check"></i><b>8</b> Manipulación de datos ordenados usando {dplyr} y {tidyr} II</a>
<ul>
<li class="chapter" data-level="8.1" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#de-ancho-a-largo-con-pivot_longer-1"><i class="fa fa-check"></i><b>8.1</b> De ancho a largo con <code>pivot_longer()</code></a></li>
<li class="chapter" data-level="8.2" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#de-largo-a-ancho-con-pivot_wider-1"><i class="fa fa-check"></i><b>8.2</b> De largo a ancho con <code>pivot_wider()</code></a></li>
<li class="chapter" data-level="8.3" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#uniendo-tablas-1"><i class="fa fa-check"></i><b>8.3</b> Uniendo tablas</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="reportes-ii.html"><a href="reportes-ii.html"><i class="fa fa-check"></i><b>9</b> Reportes II</a>
<ul>
<li class="chapter" data-level="9.1" data-path="reportes-ii.html"><a href="reportes-ii.html#eligiendo-el-formato-de-salida"><i class="fa fa-check"></i><b>9.1</b> Eligiendo el formato de salida</a></li>
<li class="chapter" data-level="9.2" data-path="reportes-ii.html"><a href="reportes-ii.html#personalizando-la-salida"><i class="fa fa-check"></i><b>9.2</b> Personalizando la salida</a></li>
<li class="chapter" data-level="9.3" data-path="reportes-ii.html"><a href="reportes-ii.html#reportes-parametrizados"><i class="fa fa-check"></i><b>9.3</b> Reportes parametrizados</a></li>
<li class="chapter" data-level="9.4" data-path="reportes-ii.html"><a href="reportes-ii.html#control-de-chunks"><i class="fa fa-check"></i><b>9.4</b> Control de chunks</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="tablas.html"><a href="tablas.html"><i class="fa fa-check"></i><b>10</b> Tablas</a>
<ul>
<li class="chapter" data-level="10.1" data-path="tablas.html"><a href="tablas.html#tablas-simples-con-kable"><i class="fa fa-check"></i><b>10.1</b> Tablas simples con <code>kable</code></a></li>
<li class="chapter" data-level="10.2" data-path="tablas.html"><a href="tablas.html#supertablas-con-kableextra"><i class="fa fa-check"></i><b>10.2</b> Supertablas con {kableExtra}</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="apariencia-de-gráficos.html"><a href="apariencia-de-gráficos.html"><i class="fa fa-check"></i><b>11</b> Apariencia de gráficos</a>
<ul>
<li class="chapter" data-level="11.1" data-path="apariencia-de-gráficos.html"><a href="apariencia-de-gráficos.html#escalas"><i class="fa fa-check"></i><b>11.1</b> Escalas</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="apariencia-de-gráficos.html"><a href="apariencia-de-gráficos.html#escala-de-colores-y-otras"><i class="fa fa-check"></i><b>11.1.1</b> Escala de colores y otras</a></li>
<li class="chapter" data-level="11.1.2" data-path="apariencia-de-gráficos.html"><a href="apariencia-de-gráficos.html#escalas-de-ejes"><i class="fa fa-check"></i><b>11.1.2</b> Escalas de ejes</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="apariencia-de-gráficos.html"><a href="apariencia-de-gráficos.html#elementos-de-texto"><i class="fa fa-check"></i><b>11.2</b> Elementos de texto</a></li>
<li class="chapter" data-level="11.3" data-path="apariencia-de-gráficos.html"><a href="apariencia-de-gráficos.html#temas"><i class="fa fa-check"></i><b>11.3</b> Temas</a></li>
</ul></li>
<li class="appendix"><span><b>Apéndice</b></span></li>
<li class="chapter" data-level="A" data-path="desafíos-de-práctica.html"><a href="desafíos-de-práctica.html"><i class="fa fa-check"></i><b>A</b> Desafíos de práctica</a>
<ul>
<li class="chapter" data-level="" data-path="desafíos-de-práctica.html"><a href="desafíos-de-práctica.html#desafío-1"><i class="fa fa-check"></i>Desafío 1</a></li>
<li class="chapter" data-level="" data-path="desafíos-de-práctica.html"><a href="desafíos-de-práctica.html#desafío-2"><i class="fa fa-check"></i>Desafío 2</a></li>
<li class="chapter" data-level="" data-path="desafíos-de-práctica.html"><a href="desafíos-de-práctica.html#desafío-3"><i class="fa fa-check"></i>Desafío 3</a></li>
<li class="chapter" data-level="" data-path="desafíos-de-práctica.html"><a href="desafíos-de-práctica.html#desafío-4"><i class="fa fa-check"></i>Desafío 4</a></li>
</ul></li>
<li class="chapter" data-level="B" data-path="instalando-r-y-rstudio.html"><a href="instalando-r-y-rstudio.html"><i class="fa fa-check"></i><b>B</b> Instalando R y RStudio</a>
<ul>
<li class="chapter" data-level="" data-path="instalando-r-y-rstudio.html"><a href="instalando-r-y-rstudio.html#instalando-r"><i class="fa fa-check"></i>Instalando R</a>
<ul>
<li class="chapter" data-level="" data-path="instalando-r-y-rstudio.html"><a href="instalando-r-y-rstudio.html#windows"><i class="fa fa-check"></i>Windows</a></li>
<li class="chapter" data-level="" data-path="instalando-r-y-rstudio.html"><a href="instalando-r-y-rstudio.html#ubuntu-o-derivados"><i class="fa fa-check"></i>Ubuntu o derivados</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="instalando-r-y-rstudio.html"><a href="instalando-r-y-rstudio.html#instalando-rstudio"><i class="fa fa-check"></i>Instalando RStudio</a>
<ul>
<li class="chapter" data-level="" data-path="instalando-r-y-rstudio.html"><a href="instalando-r-y-rstudio.html#windows-1"><i class="fa fa-check"></i>Windows</a></li>
<li class="chapter" data-level="" data-path="instalando-r-y-rstudio.html"><a href="instalando-r-y-rstudio.html#ubuntu-o-derivados-1"><i class="fa fa-check"></i>Ubuntu o derivados</a></li>
</ul></li>
<<<<<<< HEAD
=======
<li class="chapter" data-level="7.18" data-path="elementos-de-texto.html"><a href="elementos-de-texto.html"><i class="fa fa-check"></i><b>7.18</b> Elementos de texto</a></li>
<li class="chapter" data-level="7.19" data-path="temas.html"><a href="temas.html"><i class="fa fa-check"></i><b>7.19</b> Temas</a></li>
>>>>>>> dplyr-1
=======
=======
>>>>>>> Stashed changes
<li class="chapter" data-level="3" data-path="introducción-a-rmarkdown.html"><a href="introducción-a-rmarkdown.html"><i class="fa fa-check"></i><b>3</b> Introducción a RMarkdown</a>
<ul>
<li class="chapter" data-level="3.1" data-path="introducción-a-rmarkdown.html"><a href="introducción-a-rmarkdown.html#creando-archivos-.rmd"><i class="fa fa-check"></i><b>3.1</b> Creando archivos .Rmd</a></li>
<li class="chapter" data-level="3.2" data-path="introducción-a-rmarkdown.html"><a href="introducción-a-rmarkdown.html#estructura-de-un-.rmd"><i class="fa fa-check"></i><b>3.2</b> Estructura de un .Rmd</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="introducción-a-rmarkdown.html"><a href="introducción-a-rmarkdown.html#encabezado"><i class="fa fa-check"></i><b>3.2.1</b> Encabezado</a></li>
<li class="chapter" data-level="3.2.2" data-path="introducción-a-rmarkdown.html"><a href="introducción-a-rmarkdown.html#bloques-de-código"><i class="fa fa-check"></i><b>3.2.2</b> Bloques de código</a></li>
<li class="chapter" data-level="3.2.3" data-path="introducción-a-rmarkdown.html"><a href="introducción-a-rmarkdown.html#el-texto-propio-del-documento."><i class="fa fa-check"></i><b>3.2.3</b> El texto propio del documento.</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="introducción-a-rmarkdown.html"><a href="introducción-a-rmarkdown.html#markdown"><i class="fa fa-check"></i><b>3.3</b> Markdown</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="lectura-de-datos-ordenados.html"><a href="lectura-de-datos-ordenados.html"><i class="fa fa-check"></i><b>4</b> Lectura de datos ordenados</a>
<ul>
<li class="chapter" data-level="4.1" data-path="lectura-de-datos-ordenados.html"><a href="lectura-de-datos-ordenados.html#descargando-datos"><i class="fa fa-check"></i><b>4.1</b> Descargando datos</a></li>
<li class="chapter" data-level="4.2" data-path="lectura-de-datos-ordenados.html"><a href="lectura-de-datos-ordenados.html#leer-datos-csv"><i class="fa fa-check"></i><b>4.2</b> Leer datos csv</a></li>
<li class="chapter" data-level="4.3" data-path="lectura-de-datos-ordenados.html"><a href="lectura-de-datos-ordenados.html#leer-datos-de-excel"><i class="fa fa-check"></i><b>4.3</b> Leer datos de excel</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="manipulación-de-datos-ordenados.html"><a href="manipulación-de-datos-ordenados.html"><i class="fa fa-check"></i><b>5</b> Manipulación de datos ordenados</a>
<ul>
<li class="chapter" data-level="5.1" data-path="manipulación-de-datos-ordenados.html"><a href="manipulación-de-datos-ordenados.html#seleccionando-columnas-con-select"><i class="fa fa-check"></i><b>5.1</b> Seleccionando columnas con <code>select()</code></a></li>
<li class="chapter" data-level="5.2" data-path="manipulación-de-datos-ordenados.html"><a href="manipulación-de-datos-ordenados.html#filtrando-filas-con-filter"><i class="fa fa-check"></i><b>5.2</b> Filtrando filas con <code>filter()</code></a></li>
<li class="chapter" data-level="5.3" data-path="manipulación-de-datos-ordenados.html"><a href="manipulación-de-datos-ordenados.html#agrupando-y-reduciendo-con-group_by-summarise"><i class="fa fa-check"></i><b>5.3</b> Agrupando y reduciendo con <code>group_by() %&gt;% summarise()</code></a></li>
<li class="chapter" data-level="5.4" data-path="manipulación-de-datos-ordenados.html"><a href="manipulación-de-datos-ordenados.html#creando-nuevas-columnas-con-mutate"><i class="fa fa-check"></i><b>5.4</b> Creando nuevas columnas con <code>mutate()</code></a></li>
<li class="chapter" data-level="5.5" data-path="manipulación-de-datos-ordenados.html"><a href="manipulación-de-datos-ordenados.html#desagrupando-con-ungroup"><i class="fa fa-check"></i><b>5.5</b> Desagrupando con <code>ungroup()</code></a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"><i class="fa fa-check"></i><b>6</b> Manipulación de datos ordenados usando {dplyr} y {tidyr} II</a>
<ul>
<li class="chapter" data-level="6.1" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html#de-ancho-a-largo-con-pivot_longer"><i class="fa fa-check"></i><b>6.1</b> De ancho a largo con <code>pivot_longer()</code></a></li>
<li class="chapter" data-level="6.2" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html#de-largo-a-ancho-con-pivot_wider"><i class="fa fa-check"></i><b>6.2</b> De largo a ancho con <code>pivot_wider()</code></a></li>
<li class="chapter" data-level="6.3" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html#uniendo-tablas"><i class="fa fa-check"></i><b>6.3</b> Uniendo tablas</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html"><i class="fa fa-check"></i><b>7</b> Manipulación de datos ordenados usando {dplyr} y {tidyr} II</a>
<ul>
<li class="chapter" data-level="7.1" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#de-ancho-a-largo-con-pivot_longer-1"><i class="fa fa-check"></i><b>7.1</b> De ancho a largo con <code>pivot_longer()</code></a></li>
<li class="chapter" data-level="7.2" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#de-largo-a-ancho-con-pivot_wider-1"><i class="fa fa-check"></i><b>7.2</b> De largo a ancho con <code>pivot_wider()</code></a></li>
<li class="chapter" data-level="7.3" data-path="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#uniendo-tablas-1"><i class="fa fa-check"></i><b>7.3</b> Uniendo tablas</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="reportes-ii.html"><a href="reportes-ii.html"><i class="fa fa-check"></i><b>8</b> Reportes II</a>
<ul>
<li class="chapter" data-level="8.1" data-path="reportes-ii.html"><a href="reportes-ii.html#eligiendo-el-formato-de-salida"><i class="fa fa-check"></i><b>8.1</b> Eligiendo el formato de salida</a></li>
<li class="chapter" data-level="8.2" data-path="reportes-ii.html"><a href="reportes-ii.html#personalizando-la-salida"><i class="fa fa-check"></i><b>8.2</b> Personalizando la salida</a></li>
<li class="chapter" data-level="8.3" data-path="reportes-ii.html"><a href="reportes-ii.html#reportes-parametrizados"><i class="fa fa-check"></i><b>8.3</b> Reportes parametrizados</a></li>
<li class="chapter" data-level="8.4" data-path="reportes-ii.html"><a href="reportes-ii.html#control-de-chunks"><i class="fa fa-check"></i><b>8.4</b> Control de chunks</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="tablas.html"><a href="tablas.html"><i class="fa fa-check"></i><b>9</b> Tablas</a>
<ul>
<li class="chapter" data-level="9.1" data-path="tablas.html"><a href="tablas.html#tablas-simples-con-kable"><i class="fa fa-check"></i><b>9.1</b> Tablas simples con <code>kable</code></a></li>
<li class="chapter" data-level="9.2" data-path="tablas.html"><a href="tablas.html#supertablas-con-kableextra"><i class="fa fa-check"></i><b>9.2</b> Supertablas con {kableExtra}</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="apariencia-de-gráficos.html"><a href="apariencia-de-gráficos.html"><i class="fa fa-check"></i><b>10</b> Apariencia de gráficos</a>
<ul>
<li class="chapter" data-level="10.1" data-path="apariencia-de-gráficos.html"><a href="apariencia-de-gráficos.html#escalas"><i class="fa fa-check"></i><b>10.1</b> Escalas</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="apariencia-de-gráficos.html"><a href="apariencia-de-gráficos.html#escala-de-colores-y-otras"><i class="fa fa-check"></i><b>10.1.1</b> Escala de colores y otras</a></li>
<li class="chapter" data-level="10.1.2" data-path="apariencia-de-gráficos.html"><a href="apariencia-de-gráficos.html#escalas-de-ejes"><i class="fa fa-check"></i><b>10.1.2</b> Escalas de ejes</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="apariencia-de-gráficos.html"><a href="apariencia-de-gráficos.html#elementos-de-texto"><i class="fa fa-check"></i><b>10.2</b> Elementos de texto</a></li>
<li class="chapter" data-level="10.3" data-path="apariencia-de-gráficos.html"><a href="apariencia-de-gráficos.html#temas"><i class="fa fa-check"></i><b>10.3</b> Temas</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="desafíos-de-práctica.html"><a href="desafíos-de-práctica.html"><i class="fa fa-check"></i><b>11</b> Desafíos de práctica</a>
<ul>
<li class="chapter" data-level="11.1" data-path="desafíos-de-práctica.html"><a href="desafíos-de-práctica.html#desafío-1"><i class="fa fa-check"></i><b>11.1</b> Desafío 1</a></li>
<li class="chapter" data-level="11.2" data-path="desafíos-de-práctica.html"><a href="desafíos-de-práctica.html#desafío-2"><i class="fa fa-check"></i><b>11.2</b> Desafío 2</a></li>
<li class="chapter" data-level="11.3" data-path="desafíos-de-práctica.html"><a href="desafíos-de-práctica.html#desafío-3"><i class="fa fa-check"></i><b>11.3</b> Desafío 3</a></li>
<li class="chapter" data-level="11.4" data-path="desafíos-de-práctica.html"><a href="desafíos-de-práctica.html#desafío-4"><i class="fa fa-check"></i><b>11.4</b> Desafío 4</a></li>
</ul></li>
<li class="appendix"><span><b>Apéndice</b></span></li>
<li class="chapter" data-level="A" data-path="instalando-r-y-rstudio.html"><a href="instalando-r-y-rstudio.html"><i class="fa fa-check"></i><b>A</b> Instalando R y RStudio</a>
<ul>
<li class="chapter" data-level="A.1" data-path="instalando-r-y-rstudio.html"><a href="instalando-r-y-rstudio.html#instalando-r"><i class="fa fa-check"></i><b>A.1</b> Instalando R</a>
<ul>
<li class="chapter" data-level="" data-path="instalando-r-y-rstudio.html"><a href="instalando-r-y-rstudio.html#windows"><i class="fa fa-check"></i>Windows</a></li>
<li class="chapter" data-level="" data-path="instalando-r-y-rstudio.html"><a href="instalando-r-y-rstudio.html#ubuntu-o-derivados"><i class="fa fa-check"></i>Ubuntu o derivados</a></li>
</ul></li>
<li class="chapter" data-level="A.2" data-path="instalando-r-y-rstudio.html"><a href="instalando-r-y-rstudio.html#instalando-rstudio"><i class="fa fa-check"></i><b>A.2</b> Instalando RStudio</a>
<ul>
<li class="chapter" data-level="" data-path="instalando-r-y-rstudio.html"><a href="instalando-r-y-rstudio.html#windows-1"><i class="fa fa-check"></i>Windows</a></li>
<li class="chapter" data-level="" data-path="instalando-r-y-rstudio.html"><a href="instalando-r-y-rstudio.html#ubuntu-o-derivados-1"><i class="fa fa-check"></i>Ubuntu o derivados</a></li>
</ul></li>
<<<<<<< Updated upstream
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
>>>>>>> ggplot2
</ul></li>
<li class="divider"></li>
<li><b><a href="http://www.yvera.gob.ar/estadistica" target="blank">Estadísticas de Turismo</a></b></li>
<li><a href="http://datos.yvera.gob.ar/" target="blank">Datos Abiertos de Turismo</a></li>
<li><a href="https://tableros.yvera.tur.ar/" target="blank">Tableros y Reportes</a></li>
<li><a href="https://www.yvera.tur.ar/estadistica/informe" target="blank">Informes</a></li>
<li><a href="https://armonizacion.yvera.tur.ar/" target="blank">Armonización</a></li>
<li><a href="https://bitacora.yvera.tur.ar/" target="blank">Bitácora</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Documento Técnico N°6: Ciencia de Datos para el Turismo</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<link href="style.css" rel="stylesheet">
<div class="hero-image-container"> 
  <img class= "hero-image" src="imagenes/cabezal.png">
</div>
<<<<<<< HEAD
<div id="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1" class="section level1" number="8">
<h1><span class="header-section-number">Capítulo 8</span> Manipulación de datos ordenados usando {dplyr} y {tidyr} II</h1>
=======
<<<<<<< Updated upstream
<<<<<<< Updated upstream
<<<<<<< HEAD
<div id="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1" class="section level1">
<h1><span class="header-section-number">Capítulo 8</span> Manipulación de datos ordenados usando {dplyr} y {tidyr} II</h1>
=======
<div id="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1" class="section level2" number="7.4">
<h2><span class="header-section-number">7.4</span> Manipulación de datos ordenados usando {dplyr} y {tidyr} II</h2>
>>>>>>> dplyr-1
=======
<div id="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1" class="section level1" number="7">
<h1><span class="header-section-number">Capítulo 7</span> Manipulación de datos ordenados usando {dplyr} y {tidyr} II</h1>
>>>>>>> Stashed changes
=======
<div id="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1" class="section level1" number="7">
<h1><span class="header-section-number">Capítulo 7</span> Manipulación de datos ordenados usando {dplyr} y {tidyr} II</h1>
>>>>>>> Stashed changes
>>>>>>> ggplot2
<p>En <a href="04-lectura-datos.html#Formatos_de_tablas">la última sección de lectura de datos</a> viste el concepto de datos “anchos” y “largos”.</p>
<p>Los datos en formato “largo” o “tidy”, son aquellos en los cuales:</p>
<ul>
<li>cada fila es una observación</li>
<li>cada columna es una variable</li>
</ul>
<p>En el formato “ancho” es un poco más complejo de definirlo pero la idea general es que:</p>
<ul>
<li>cada fila es un “item”</li>
<li>cada columna es una variable</li>
</ul>
<p><img src="img/largo-ancho.png" /></p>
<p>Una tabla en formato largo va a tener una cierta cantidad de columnas que cumplen el rol de <em>identificadores</em> y cuya combinación identifican una única observación y una única columna con el valor de la observación.
En el ejemplo de arriba, <code>pais</code> y <code>anio</code> son las columnas identificadoras y <code>casos</code> es la columna que contiene el valor de las observaciones.</p>
<p>En una tabla ancha, cada observación única se identifica a partir de la intersección de filas y columnas.
En el ejemplo, los países están en las filas y los años en las columnas.</p>
<p>En general, el formato ancho es más compacto y legible por humanos mientras que el largo es más fácil de manejar con la computadora.
Si te fijás en las tablas de arriba, es más fácil comparar los valores entre países y entre años en la tabla ancha.
Pero el nombre de las columnas (“1999”, “2000”) en realidad ¡son datos!
Además este formato se empieza a complicar en cuanto hay más de dos identificadores.</p>
<p>Un mismo set de datos puede ser representado de forma completamente “larga”, completamente “ancha” o –lo que es más común– en un formato intermedio pero no existe una forma “correcta” de organizar los datos; cada una tiene sus ventajas y desventajas.
Por esto es que es muy normal que durante un análisis los datos vayan y vuelvan entre distintos formatos dependiendo de los métodos estadísticos que se le aplican.
Entonces, aprender a transformar datos anchos en largos y viceversa es un habilidad muy útil.</p>
<div class="alert alert-info">
<p><strong>Desafío</strong></p>
<p>En las tablas de ejemplo cada país tiene el un valor observado de “casos” para cada año.
¿Cómo agregarías una nueva variable con información sobre “precios”?
Dibujá un esquema en papel y lápiz en formato ancho y uno en formato largo.
¿En qué formato es más “natural” esa extensión?</p>
</div>
<p>En esta sección vas a usar el paquete {tidyr} para manipular datos.
Si no lo tenés instalado, instalalo con el comando:</p>
<<<<<<< Updated upstream
<<<<<<< HEAD
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb132-1"></a><span class="kw">install.packages</span>(<span class="st">&quot;tidyr&quot;</span>)</span></code></pre></div>
=======
<<<<<<< Updated upstream
<<<<<<< HEAD
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb140-1"></a><span class="kw">install.packages</span>(<span class="st">&quot;tidyr&quot;</span>)</span></code></pre></div>
>>>>>>> ggplot2
<p>(como siempre, recordá que esto hay que hacerlo una única vez)</p>
<p>Y luego cargá {tidyr} y {dplyr} (que usaste en <a href="05-dplyr-I.html">una sección anterior</a>) con:</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb133-1"></a><span class="kw">library</span>(tidyr)</span>
<span id="cb133-2"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb133-2"></a><span class="kw">library</span>(dplyr)</span></code></pre></div>
<div id="de-ancho-a-largo-con-pivot_longer-1" class="section level2">
<h2><span class="header-section-number">8.1</span> De ancho a largo con <code>pivot_longer()</code></h2>
<p>En secciones anteriores usaste una versión de los datos de <a href="https://www.gapminder.org/">gapminder</a>.
Ahora vas a leer los datos en su formato original:</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb134-1"></a>paises_ancho &lt;-<span class="st"> </span>readr<span class="op">::</span><span class="kw">read_csv</span>(<span class="st">&quot;datos/paises_ancho.csv&quot;</span>)</span></code></pre></div>
=======
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb131-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;tidyr&quot;</span>)</span></code></pre></div>
<p>(como siempre, recordá que esto hay que hacerlo una única vez)</p>
<p>Y luego cargá {tidyr} y {dplyr} (que usaste en <a href="05-dplyr-I.html">una sección anterior</a>) con:</p>
<<<<<<< HEAD
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb132-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb132-2"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb132-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div>
<div id="de-ancho-a-largo-con-pivot_longer-1" class="section level2" number="8.1">
<h2><span class="header-section-number">8.1</span> De ancho a largo con <code>pivot_longer()</code></h2>
<p>En secciones anteriores usaste una versión de los datos de <a href="https://www.gapminder.org/">gapminder</a>.
Ahora vas a leer los datos en su formato original:</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb133-1" aria-hidden="true" tabindex="-1"></a>paises_ancho <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(<span class="st">&quot;datos/paises_ancho.csv&quot;</span>)</span></code></pre></div>
>>>>>>> Stashed changes
=======
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb163-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb163-2"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb163-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div>
>>>>>>> dplyr-1
=======
=======
>>>>>>> Stashed changes
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;tidyr&quot;</span>)</span></code></pre></div>
<p>(como siempre, recordá que esto hay que hacerlo una única vez)</p>
<p>Y luego cargá {tidyr} y {dplyr} (que usaste en <a href="05-dplyr-I.html">una sección anterior</a>) con:</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb97-2"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb97-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div>
<div id="de-ancho-a-largo-con-pivot_longer-1" class="section level2" number="7.1">
<h2><span class="header-section-number">7.1</span> De ancho a largo con <code>pivot_longer()</code></h2>
<p>En secciones anteriores usaste una versión de los datos de <a href="https://www.gapminder.org/">gapminder</a>.
Ahora vas a leer los datos en su formato original:</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb98-1" aria-hidden="true" tabindex="-1"></a>paises_ancho <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(<span class="st">&quot;datos/paises_ancho.csv&quot;</span>)</span></code></pre></div>
>>>>>>> ggplot2
<pre><code>## Rows: 142 Columns: 38</code></pre>
<pre><code>## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr  (2): continente, pais
## dbl (36): pib_per_capita_1952, pib_per_capita_1957, pib_per_capita_1962, pib...</code></pre>
<pre><code>## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<<<<<<< HEAD
<<<<<<< Updated upstream
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb138-1"></a>paises_ancho</span></code></pre></div>
=======
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb137-1" aria-hidden="true" tabindex="-1"></a>paises_ancho</span></code></pre></div>
>>>>>>> Stashed changes
=======
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb102-1" aria-hidden="true" tabindex="-1"></a>paises_ancho</span></code></pre></div>
>>>>>>> ggplot2
<pre><code>## # A tibble: 142 × 38
##    continente pais                     pib_per_capita_… pib_per_capita_… pib_per_capita_…
##    &lt;chr&gt;      &lt;chr&gt;                               &lt;dbl&gt;            &lt;dbl&gt;            &lt;dbl&gt;
##  1 Africa     Algeria                             2449.            3014.            2551.
##  2 Africa     Angola                              3521.            3828.            4269.
##  3 Africa     Benin                               1063.             960.             949.
##  4 Africa     Botswana                             851.             918.             984.
##  5 Africa     Burkina Faso                         543.             617.             723.
##  6 Africa     Burundi                              339.             380.             355.
##  7 Africa     Cameroon                            1173.            1313.            1400.
##  8 Africa     Central African Republic            1071.            1191.            1193.
##  9 Africa     Chad                                1179.            1308.            1390.
## 10 Africa     Comoros                             1103.            1211.            1407.
## # … with 132 more rows, and 33 more variables: pib_per_capita_1967 &lt;dbl&gt;,
## #   pib_per_capita_1972 &lt;dbl&gt;, pib_per_capita_1977 &lt;dbl&gt;,
## #   pib_per_capita_1982 &lt;dbl&gt;, pib_per_capita_1987 &lt;dbl&gt;,
## #   pib_per_capita_1992 &lt;dbl&gt;, pib_per_capita_1997 &lt;dbl&gt;,
## #   pib_per_capita_2002 &lt;dbl&gt;, pib_per_capita_2007 &lt;dbl&gt;,
## #   esperanza_de_vida_1952 &lt;dbl&gt;, esperanza_de_vida_1957 &lt;dbl&gt;,
## #   esperanza_de_vida_1962 &lt;dbl&gt;, esperanza_de_vida_1967 &lt;dbl&gt;, …</code></pre>
<div class="alert alert-success">
<p>¿Notaste que en el código anterior no usaste <code>library(readr)</code> para cargar el paquete y luego leer?
Con la notación <code>paquete::funcion()</code> podés acceder a las funciones de un paquete sin tener que cargarlo.
Es una buena forma de no tener que cargar un montón de paquetes innecesarios si vas a correr una única función de un paquete pocas veces.</p>
</div>
<p>Esta tabla, increíblemente ancha, es muy difícil de manejar.
Por ejemplo, es imposible hacer una serie de tiempo de una variable, o calcular el promedio por variable y país; ni hablar de calcular una regresión lineal.</p>
<p>Para convertirlo en una tabla más larga, se usa <code>pivot_longer()</code> (“longer” es “más largo” en inglés):</p>
<<<<<<< HEAD
<<<<<<< Updated upstream
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb140-1"></a>paises_largo &lt;-<span class="st"> </span><span class="kw">pivot_longer</span>(paises_ancho,</span>
<span id="cb140-2"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb140-2"></a>                             <span class="dt">cols =</span> <span class="kw">c</span>(<span class="kw">starts_with</span>(<span class="st">&#39;pob&#39;</span>), </span>
<span id="cb140-3"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb140-3"></a>                                      <span class="kw">starts_with</span>(<span class="st">&#39;esperanza&#39;</span>), </span>
<span id="cb140-4"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb140-4"></a>                                      <span class="kw">starts_with</span>(<span class="st">&#39;pib_per&#39;</span>)),</span>
<span id="cb140-5"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb140-5"></a>                             <span class="dt">names_to =</span> <span class="st">&quot;variable_anio&quot;</span>, </span>
<span id="cb140-6"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb140-6"></a>                             <span class="dt">values_to =</span> <span class="st">&quot;valor&quot;</span></span>
<span id="cb140-7"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb140-7"></a>)</span>
<span id="cb140-8"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb140-8"></a>paises_largo</span></code></pre></div>
=======
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb139-1" aria-hidden="true" tabindex="-1"></a>paises_largo <span class="ot">&lt;-</span> <span class="fu">pivot_longer</span>(paises_ancho,</span>
<span id="cb139-2"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb139-2" aria-hidden="true" tabindex="-1"></a>                             <span class="at">cols =</span> <span class="fu">c</span>(<span class="fu">starts_with</span>(<span class="st">&#39;pob&#39;</span>), </span>
<span id="cb139-3"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb139-3" aria-hidden="true" tabindex="-1"></a>                                      <span class="fu">starts_with</span>(<span class="st">&#39;esperanza&#39;</span>), </span>
<span id="cb139-4"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb139-4" aria-hidden="true" tabindex="-1"></a>                                      <span class="fu">starts_with</span>(<span class="st">&#39;pib_per&#39;</span>)),</span>
<span id="cb139-5"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb139-5" aria-hidden="true" tabindex="-1"></a>                             <span class="at">names_to =</span> <span class="st">&quot;variable_anio&quot;</span>, </span>
<span id="cb139-6"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb139-6" aria-hidden="true" tabindex="-1"></a>                             <span class="at">values_to =</span> <span class="st">&quot;valor&quot;</span></span>
<span id="cb139-7"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb139-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb139-8"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb139-8" aria-hidden="true" tabindex="-1"></a>paises_largo</span></code></pre></div>
>>>>>>> Stashed changes
=======
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb104-1" aria-hidden="true" tabindex="-1"></a>paises_largo <span class="ot">&lt;-</span> <span class="fu">pivot_longer</span>(paises_ancho,</span>
<span id="cb104-2"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb104-2" aria-hidden="true" tabindex="-1"></a>                             <span class="at">cols =</span> <span class="fu">c</span>(<span class="fu">starts_with</span>(<span class="st">&#39;pob&#39;</span>), </span>
<span id="cb104-3"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb104-3" aria-hidden="true" tabindex="-1"></a>                                      <span class="fu">starts_with</span>(<span class="st">&#39;esperanza&#39;</span>), </span>
<span id="cb104-4"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb104-4" aria-hidden="true" tabindex="-1"></a>                                      <span class="fu">starts_with</span>(<span class="st">&#39;pib_per&#39;</span>)),</span>
<span id="cb104-5"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb104-5" aria-hidden="true" tabindex="-1"></a>                             <span class="at">names_to =</span> <span class="st">&quot;variable_anio&quot;</span>, </span>
<span id="cb104-6"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb104-6" aria-hidden="true" tabindex="-1"></a>                             <span class="at">values_to =</span> <span class="st">&quot;valor&quot;</span></span>
<span id="cb104-7"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb104-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb104-8"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb104-8" aria-hidden="true" tabindex="-1"></a>paises_largo</span></code></pre></div>
>>>>>>> ggplot2
<pre><code>## # A tibble: 5,112 × 4
##    continente pais    variable_anio     valor
##    &lt;chr&gt;      &lt;chr&gt;   &lt;chr&gt;             &lt;dbl&gt;
##  1 Africa     Algeria poblacion_1952  9279525
##  2 Africa     Algeria poblacion_1957 10270856
##  3 Africa     Algeria poblacion_1962 11000948
##  4 Africa     Algeria poblacion_1967 12760499
##  5 Africa     Algeria poblacion_1972 14760787
##  6 Africa     Algeria poblacion_1977 17152804
##  7 Africa     Algeria poblacion_1982 20033753
##  8 Africa     Algeria poblacion_1987 23254956
##  9 Africa     Algeria poblacion_1992 26298373
## 10 Africa     Algeria poblacion_1997 29072015
## # … with 5,102 more rows</code></pre>
<p>El primer argumento de<code>pivot_longer()</code> es la tabla que va a modificar: <code>paises_ancho</code>.
El segundo argumento se llama <code>cols</code> y es un vector con las columnas que tienen los valores a “alargar”.
Podría ser un vector escrito a mano (algo como <code>c("pib_per_capita_1952", "pib_per_capita_1957"...)</code>) pero con más de 30 columnas, escribir todo eso sería tedioso y probablemente estaría lleno de errores.
Por eso {tidyr} provee funciones de ayuda para seleccionar columnas en base a patrones.
El código de arriba usa <code>starts_with()</code> que, como su nombre en inglés lo indica, selecciona las columnas que <em>empiezan con</em> una determinada cadena de caracteres.
El vector <code>c(starts_with('pob'), starts_with('esperanza'), starts_with('pib_per'))</code> le dice a <code>pivot_longer()</code> que seleccione las columnas que empieza con “pob”, las que empiezan con “esperanza” y las que empiezan con “pib_per”.</p>
<div class="alert alert-success">
<p>Estas funciones accesorias para seleccionar muchas funciones se llaman “tidyselect”.
Si querés leer más detalles de las distintas formas que podés seleccionar variables leé la documentación usando <code>?tidyselect::language</code>.</p>
</div>
<p>El tercer y cuarto argumento son los nombres de las columnas de “nombre” y de “valor” que va a tener la nueva tabla.
Como la nueva columna de identificación tiene los datos de la variable y el año a medir, “variable_anio” es un buen nombre.
Y la columna de valor va a tener… bueno, el valor.</p>
<p>Tomate un momento para visualizar lo que acaba de pasar.
La tabla ancha tenía un montón de columnas con distintos datos.
Ahora estos datos están uno arriba de otro en la columna “valor”, pero para identificar el nombre de la columna de la cual vinieron, se agrega la columna “variable_anio”.</p>
<div class="figure">
<img src="img/ancho-a-largo.png" alt="" />
<p class="caption">Proceso de largo a ancho</p>
</div>
<p>La columna <code>variable_anio</code> todavía no es muy útil porque contiene 2 datos, la variable (población, expectativa de vida o PBI per cápita) y el año.
Sería mejor separar esta información en dos columnas llamadas “variable” y “anio”.
Para eso está la función <code>separate()</code>.</p>
<<<<<<< HEAD
<<<<<<< Updated upstream
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb142-1"></a><span class="kw">separate</span>(paises_largo, </span>
<span id="cb142-2"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb142-2"></a>         <span class="dt">col =</span> variable_anio, </span>
<span id="cb142-3"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb142-3"></a>         <span class="dt">into =</span> <span class="kw">c</span>(<span class="st">&quot;variable&quot;</span>, <span class="st">&quot;anio&quot;</span>), </span>
<span id="cb142-4"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb142-4"></a>         <span class="dt">sep =</span> <span class="dv">-4</span>)</span></code></pre></div>
=======
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb141-1" aria-hidden="true" tabindex="-1"></a><span class="fu">separate</span>(paises_largo, </span>
<span id="cb141-2"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb141-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">col =</span> variable_anio, </span>
<span id="cb141-3"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb141-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">into =</span> <span class="fu">c</span>(<span class="st">&quot;variable&quot;</span>, <span class="st">&quot;anio&quot;</span>), </span>
<span id="cb141-4"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb141-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">sep =</span> <span class="sc">-</span><span class="dv">4</span>)</span></code></pre></div>
>>>>>>> Stashed changes
=======
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="fu">separate</span>(paises_largo, </span>
<span id="cb106-2"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb106-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">col =</span> variable_anio, </span>
<span id="cb106-3"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb106-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">into =</span> <span class="fu">c</span>(<span class="st">&quot;variable&quot;</span>, <span class="st">&quot;anio&quot;</span>), </span>
<span id="cb106-4"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb106-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">sep =</span> <span class="sc">-</span><span class="dv">4</span>)</span></code></pre></div>
>>>>>>> ggplot2
<pre><code>## # A tibble: 5,112 × 5
##    continente pais    variable   anio     valor
##    &lt;chr&gt;      &lt;chr&gt;   &lt;chr&gt;      &lt;chr&gt;    &lt;dbl&gt;
##  1 Africa     Algeria poblacion_ 1952   9279525
##  2 Africa     Algeria poblacion_ 1957  10270856
##  3 Africa     Algeria poblacion_ 1962  11000948
##  4 Africa     Algeria poblacion_ 1967  12760499
##  5 Africa     Algeria poblacion_ 1972  14760787
##  6 Africa     Algeria poblacion_ 1977  17152804
##  7 Africa     Algeria poblacion_ 1982  20033753
##  8 Africa     Algeria poblacion_ 1987  23254956
##  9 Africa     Algeria poblacion_ 1992  26298373
## 10 Africa     Algeria poblacion_ 1997  29072015
## # … with 5,102 more rows</code></pre>
<p>El primer argumento, como siempre, es la tabla a procesar.
El segundo, <code>col</code>, es la columna a separar en dos (o más) columnas nuevas.
El tercero, <code>into</code> es el nombre de las nuevas columnas que <code>separate()</code> va a crear.
El último argumento es <code>sep</code> que define cómo realizar la separación.
Por defecto, <code>sep</code> es una <a href="https://es.wikipedia.org/wiki/Expresi%C3%B3n_regular">expresión regular</a> que captura cualquier caracter no alfanumérico.
En el caso de <code>variable_anio</code> no sirve, porque para valores como <code>"esperanza_de_vida_1952"</code>, separaría en <code>"esperanza"</code>, <code>"de"</code>, <code>"vida"</code> y <code>"1952"</code>.
Como el año tiene siempre 4 caracteres, una solución simple es usar <code>sep = -4</code>, que significa que la separación es 4 caracteres contando desde el final.</p>
<p>Habrás notado un problema.
El texto en la columnas <code>variable</code> todavía tiene un “_” al final.
Podrías usar <code>mutate()</code> y un poco de funciones de manipulación de caracteres para quitarlo, pero hay una forma un poco más simple y es separando la columna <code>variable_anio</code> en tres, incluyendo una columna con el guión:</p>
<<<<<<< HEAD
<<<<<<< Updated upstream
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb144-1"></a>paises_largo &lt;-<span class="st"> </span><span class="kw">separate</span>(paises_largo, </span>
<span id="cb144-2"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb144-2"></a>         <span class="dt">col =</span> variable_anio, </span>
<span id="cb144-3"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb144-3"></a>         <span class="dt">into =</span> <span class="kw">c</span>(<span class="st">&quot;variable&quot;</span>, <span class="st">&quot;guion&quot;</span>, <span class="st">&quot;anio&quot;</span>), </span>
<span id="cb144-4"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb144-4"></a>         <span class="dt">sep =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">5</span>, <span class="dv">-4</span>))</span>
<span id="cb144-5"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb144-5"></a>paises_largo</span></code></pre></div>
=======
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb143-1" aria-hidden="true" tabindex="-1"></a>paises_largo <span class="ot">&lt;-</span> <span class="fu">separate</span>(paises_largo, </span>
<span id="cb143-2"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb143-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">col =</span> variable_anio, </span>
<span id="cb143-3"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb143-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">into =</span> <span class="fu">c</span>(<span class="st">&quot;variable&quot;</span>, <span class="st">&quot;guion&quot;</span>, <span class="st">&quot;anio&quot;</span>), </span>
<span id="cb143-4"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb143-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">sep =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">5</span>, <span class="sc">-</span><span class="dv">4</span>))</span>
<span id="cb143-5"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb143-5" aria-hidden="true" tabindex="-1"></a>paises_largo</span></code></pre></div>
>>>>>>> Stashed changes
=======
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb108-1" aria-hidden="true" tabindex="-1"></a>paises_largo <span class="ot">&lt;-</span> <span class="fu">separate</span>(paises_largo, </span>
<span id="cb108-2"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb108-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">col =</span> variable_anio, </span>
<span id="cb108-3"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb108-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">into =</span> <span class="fu">c</span>(<span class="st">&quot;variable&quot;</span>, <span class="st">&quot;guion&quot;</span>, <span class="st">&quot;anio&quot;</span>), </span>
<span id="cb108-4"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb108-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">sep =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">5</span>, <span class="sc">-</span><span class="dv">4</span>))</span>
<span id="cb108-5"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb108-5" aria-hidden="true" tabindex="-1"></a>paises_largo</span></code></pre></div>
>>>>>>> ggplot2
<pre><code>## # A tibble: 5,112 × 6
##    continente pais    variable  guion anio     valor
##    &lt;chr&gt;      &lt;chr&gt;   &lt;chr&gt;     &lt;chr&gt; &lt;chr&gt;    &lt;dbl&gt;
##  1 Africa     Algeria poblacion _     1952   9279525
##  2 Africa     Algeria poblacion _     1957  10270856
##  3 Africa     Algeria poblacion _     1962  11000948
##  4 Africa     Algeria poblacion _     1967  12760499
##  5 Africa     Algeria poblacion _     1972  14760787
##  6 Africa     Algeria poblacion _     1977  17152804
##  7 Africa     Algeria poblacion _     1982  20033753
##  8 Africa     Algeria poblacion _     1987  23254956
##  9 Africa     Algeria poblacion _     1992  26298373
## 10 Africa     Algeria poblacion _     1997  29072015
## # … with 5,102 more rows</code></pre>
<p>Y ya casi.
Hay que eliminar la columna <code>guion</code>, que no sirve para nada.
Pero fijate que debajo de la columna <code>anio</code> dice <code>&lt;chr&gt;</code>; eso significa que el tipo de la columna es caracter, pero los años son números.
Usando <code>mutate()</code> podés eliminar la columna <code>guion</code> asignándole el valor <code>NULL</code> (nulo) y coercer (recordá <a href="04-lectura-datos.html#Vectores">esta sección</a>) la columna <code>anio</code> a entero usando <code>as.integer()</code>:</p>
<<<<<<< HEAD
<<<<<<< Updated upstream
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb146-1"></a>paises_largo &lt;-<span class="st"> </span><span class="kw">mutate</span>(paises_largo, </span>
<span id="cb146-2"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb146-2"></a>                       <span class="dt">guion =</span> <span class="ot">NULL</span>,</span>
<span id="cb146-3"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb146-3"></a>                       <span class="dt">anio =</span> <span class="kw">as.integer</span>(anio))</span>
<span id="cb146-4"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb146-4"></a>paises_largo</span></code></pre></div>
=======
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb145-1" aria-hidden="true" tabindex="-1"></a>paises_largo <span class="ot">&lt;-</span> <span class="fu">mutate</span>(paises_largo, </span>
<span id="cb145-2"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb145-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">guion =</span> <span class="cn">NULL</span>,</span>
<span id="cb145-3"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb145-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">anio =</span> <span class="fu">as.integer</span>(anio))</span>
<span id="cb145-4"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb145-4" aria-hidden="true" tabindex="-1"></a>paises_largo</span></code></pre></div>
>>>>>>> Stashed changes
=======
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb110-1" aria-hidden="true" tabindex="-1"></a>paises_largo <span class="ot">&lt;-</span> <span class="fu">mutate</span>(paises_largo, </span>
<span id="cb110-2"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb110-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">guion =</span> <span class="cn">NULL</span>,</span>
<span id="cb110-3"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb110-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">anio =</span> <span class="fu">as.integer</span>(anio))</span>
<span id="cb110-4"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb110-4" aria-hidden="true" tabindex="-1"></a>paises_largo</span></code></pre></div>
>>>>>>> ggplot2
<pre><code>## # A tibble: 5,112 × 5
##    continente pais    variable   anio    valor
##    &lt;chr&gt;      &lt;chr&gt;   &lt;chr&gt;     &lt;int&gt;    &lt;dbl&gt;
##  1 Africa     Algeria poblacion  1952  9279525
##  2 Africa     Algeria poblacion  1957 10270856
##  3 Africa     Algeria poblacion  1962 11000948
##  4 Africa     Algeria poblacion  1967 12760499
##  5 Africa     Algeria poblacion  1972 14760787
##  6 Africa     Algeria poblacion  1977 17152804
##  7 Africa     Algeria poblacion  1982 20033753
##  8 Africa     Algeria poblacion  1987 23254956
##  9 Africa     Algeria poblacion  1992 26298373
## 10 Africa     Algeria poblacion  1997 29072015
## # … with 5,102 more rows</code></pre>
<div class="alert alert-info">
<p><strong>Desafío</strong></p>
<p>Juntá todos los pasos anteriores en una sola cadena de operaciones usando <code>%&gt;%</code>.</p>
</div>
</div>
<<<<<<< HEAD
<div id="de-largo-a-ancho-con-pivot_wider-1" class="section level2" number="8.2">
<h2><span class="header-section-number">8.2</span> De largo a ancho con <code>pivot_wider()</code></h2>
=======
<div id="de-largo-a-ancho-con-pivot_wider-1" class="section level2" number="7.2">
<h2><span class="header-section-number">7.2</span> De largo a ancho con <code>pivot_wider()</code></h2>
>>>>>>> ggplot2
<p>Ahora la variable <code>paises_largo</code> está en el formato más largo posible.
Tiene 5 columnas, de las cuales sólo una es la columnas con valores.
Pero con los datos así no podrías hacer un gráfico de puntos que muestre la relación entre el PBI per cápita y la expectativa de vida como en la <a href="06-graficos-I.html#Segunda_capa:_geometrías">sección de gráficos</a>.
Fijate que los valores de la columna <code>valor</code> no tienen todos las mismas unidades, por lo que operar con ese vector podría dar resultados sin sentido.
Muchas veces es conveniente y natural tener los datos en un formato intermedio en donde hay múltiples columnas con los valores de distintas variables observadas.</p>
<p>Pasa “ensanchar” una tabla está la función <code>pivot_wider()</code> (“wider” es “más ancha” en inglés) y el código para conseguir este formato intermedio es:</p>
<<<<<<< HEAD
<<<<<<< Updated upstream
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb148-1"></a>paises_medio &lt;-<span class="st"> </span><span class="kw">pivot_wider</span>(paises_largo, <span class="dt">names_from =</span> variable, <span class="dt">values_from =</span> valor)</span>
<span id="cb148-2"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb148-2"></a>paises_medio</span></code></pre></div>
=======
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb147-1" aria-hidden="true" tabindex="-1"></a>paises_medio <span class="ot">&lt;-</span> <span class="fu">pivot_wider</span>(paises_largo, <span class="at">names_from =</span> variable, <span class="at">values_from =</span> valor)</span>
<span id="cb147-2"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb147-2" aria-hidden="true" tabindex="-1"></a>paises_medio</span></code></pre></div>
>>>>>>> Stashed changes
=======
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb112-1" aria-hidden="true" tabindex="-1"></a>paises_medio <span class="ot">&lt;-</span> <span class="fu">pivot_wider</span>(paises_largo, <span class="at">names_from =</span> variable, <span class="at">values_from =</span> valor)</span>
<span id="cb112-2"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb112-2" aria-hidden="true" tabindex="-1"></a>paises_medio</span></code></pre></div>
>>>>>>> ggplot2
<pre><code>## # A tibble: 1,704 × 6
##    continente pais     anio poblacion esperanza_de_vida pib_per_capita
##    &lt;chr&gt;      &lt;chr&gt;   &lt;int&gt;     &lt;dbl&gt;             &lt;dbl&gt;          &lt;dbl&gt;
##  1 Africa     Algeria  1952   9279525              43.1          2449.
##  2 Africa     Algeria  1957  10270856              45.7          3014.
##  3 Africa     Algeria  1962  11000948              48.3          2551.
##  4 Africa     Algeria  1967  12760499              51.4          3247.
##  5 Africa     Algeria  1972  14760787              54.5          4183.
##  6 Africa     Algeria  1977  17152804              58.0          4910.
##  7 Africa     Algeria  1982  20033753              61.4          5745.
##  8 Africa     Algeria  1987  23254956              65.8          5681.
##  9 Africa     Algeria  1992  26298373              67.7          5023.
## 10 Africa     Algeria  1997  29072015              69.2          4797.
## # … with 1,694 more rows</code></pre>
<p>Nuevamente el primer argumento es la tabla original.
El segundo, <code>names_from</code> es la columna cuyos valores únicos van a convertirse en nuevas columnas.
La columna <code>variable</code> tiene los valores <code>"población"</code>, <code>"esperanza_de_vida"</code> y <code>"pib_per_capita"</code> y entonces la tabla nueva tendrá tres columnas con esos nombres.
El tercer argumento, <code>values_from</code>, es la columna de la cual sacar los valores.</p>
<p>Para volver al formato más ancho, basta con agregar más columnas en el argumento <code>names_from</code>:</p>
<<<<<<< HEAD
<<<<<<< Updated upstream
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb150-1"></a><span class="kw">pivot_wider</span>(paises_largo, </span>
<span id="cb150-2"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb150-2"></a>            <span class="dt">names_from =</span> <span class="kw">c</span>(variable, anio), </span>
<span id="cb150-3"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb150-3"></a>            <span class="dt">names_sep =</span> <span class="st">&quot;_&quot;</span>,</span>
<span id="cb150-4"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb150-4"></a>            <span class="dt">values_from =</span> valor)</span></code></pre></div>
=======
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb149-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pivot_wider</span>(paises_largo, </span>
<span id="cb149-2"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb149-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">names_from =</span> <span class="fu">c</span>(variable, anio), </span>
<span id="cb149-3"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb149-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">names_sep =</span> <span class="st">&quot;_&quot;</span>,</span>
<span id="cb149-4"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb149-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">values_from =</span> valor)</span></code></pre></div>
>>>>>>> Stashed changes
=======
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pivot_wider</span>(paises_largo, </span>
<span id="cb114-2"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb114-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">names_from =</span> <span class="fu">c</span>(variable, anio), </span>
<span id="cb114-3"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb114-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">names_sep =</span> <span class="st">&quot;_&quot;</span>,</span>
<span id="cb114-4"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb114-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">values_from =</span> valor)</span></code></pre></div>
>>>>>>> ggplot2
<pre><code>## # A tibble: 142 × 38
##    continente pais   poblacion_1952 poblacion_1957 poblacion_1962 poblacion_1967
##    &lt;chr&gt;      &lt;chr&gt;           &lt;dbl&gt;          &lt;dbl&gt;          &lt;dbl&gt;          &lt;dbl&gt;
##  1 Africa     Alger…        9279525       10270856       11000948       12760499
##  2 Africa     Angola        4232095        4561361        4826015        5247469
##  3 Africa     Benin         1738315        1925173        2151895        2427334
##  4 Africa     Botsw…         442308         474639         512764         553541
##  5 Africa     Burki…        4469979        4713416        4919632        5127935
##  6 Africa     Burun…        2445618        2667518        2961915        3330989
##  7 Africa     Camer…        5009067        5359923        5793633        6335506
##  8 Africa     Centr…        1291695        1392284        1523478        1733638
##  9 Africa     Chad          2682462        2894855        3150417        3495967
## 10 Africa     Comor…         153936         170928         191689         217378
## # … with 132 more rows, and 32 more variables: poblacion_1972 &lt;dbl&gt;,
## #   poblacion_1977 &lt;dbl&gt;, poblacion_1982 &lt;dbl&gt;, poblacion_1987 &lt;dbl&gt;,
## #   poblacion_1992 &lt;dbl&gt;, poblacion_1997 &lt;dbl&gt;, poblacion_2002 &lt;dbl&gt;,
## #   poblacion_2007 &lt;dbl&gt;, esperanza_de_vida_1952 &lt;dbl&gt;,
## #   esperanza_de_vida_1957 &lt;dbl&gt;, esperanza_de_vida_1962 &lt;dbl&gt;,
## #   esperanza_de_vida_1967 &lt;dbl&gt;, esperanza_de_vida_1972 &lt;dbl&gt;,
## #   esperanza_de_vida_1977 &lt;dbl&gt;, esperanza_de_vida_1982 &lt;dbl&gt;, …</code></pre>
<p>En esta llamada también está el argumento <code>names_sep</code>, que determina el caracter que se usa para crear el nombre de las nuevas columnas.</p>
<div class="alert alert-info">
<p><strong>Desafío</strong></p>
<ul>
<li><p>Creá una nueva tabla, llamada <code>paises_superduper_ancho</code> que tenga una columna para cada variable, anio y país.
(Consejo: la tabla final tiene que tener 5 filas).</p></li>
<li><p>¿Cómo es la tabla más ancha posible que podés generar con estos datos?
¿Cuántas filas y columnas tiene?</p></li>
</ul>
</div>
</div>
<<<<<<< HEAD
<div id="uniendo-tablas-1" class="section level2" number="8.3">
<h2><span class="header-section-number">8.3</span> Uniendo tablas</h2>
=======
<div id="uniendo-tablas-1" class="section level2" number="7.3">
<h2><span class="header-section-number">7.3</span> Uniendo tablas</h2>
>>>>>>> ggplot2
<p>Hasta ahora todo lo que usaste de {dplyr} involucra trabajar y modificar con una sola tabla a la vez, pero es muy común tener dos o más tablas con datos relacionados.
En ese caso, tenemos que <em>unir</em> estas tablas.
a partir de una o más variables en común o <em>keys</em>.
En Excel u otro programa de hojas de cálculo, esto se resuelve con la función “VLOOKUP” o “BUSCARV”, en R y en particular dentro del mundo de {dplyr} hay que usar la familia de funciones <code>*_join()</code>.
Hay una función cada tipo de unión que queramos hacer.</p>
<p>Asumiendo que querés unir dos data.frames o tablas <code>x</code> e <code>y</code> que tienen en común una variable <code>A</code>:</p>
<p><img src="img/join.png" /></p>
<ul>
<li><p><code>full_join()</code>: devuelve todas las filas y todas las columnas de ambas tablas <code>x</code> e <code>y</code>.
Cuando no coinciden los elementos en <code>x1</code>, devuelve <code>NA</code> (dato faltante).
Esto significa que no se pierden filas de ninguna de las dos tablas aún cuando no hay coincidencia.
Está es la manera más segura de unir tablas.</p></li>
<li><p><code>left_join()</code>: devuelve todas las filas de <code>x</code> y todas las columnas de <code>x</code> e <code>y</code>.
Las filas en <code>x</code> que no tengan coincidencia con <code>y</code> tendrán <code>NA</code> en las nuevas columnas.
Si hay múltiples coincidencias entre <code>x</code>e <code>y</code>, devuelve todas las coincidencias posibles.</p></li>
<li><p><code>right_join()</code>: es igual que <code>left_join()</code> pero intercambiando el orden de <code>x</code> e <code>y</code>.
En otras palabras, <code>right_join(x, y)</code> es idéntico a <code>left_join(y, x)</code>.</p></li>
<li><p><code>inner_join()</code>: devuelve todas las filas de <code>x</code> donde hay coincidencias con <code>y</code> y todas las columnas de <code>x</code> e <code>y</code>.
Si hay múltiples coincidencias entre <code>x</code> e <code>y</code>, entonces devuelve todas las coincidencias.
Esto significa que eliminará las filas (observaciones) que no coincidan en ambas tablas, lo que puede ser peligroso.</p></li>
</ul>
<p><img src="img/join_family.png" /></p>
<p>Ahora vamos a seguir trabajando con las base de datos de <code>paises</code> pero nos vamos a quedar solo con las observaciones del 2007 y de paso unirlo a una nueva base de datos <code>co2</code> que contiene información de la emisión de dióxido de carbono de cada país para ese mismo año.</p>
<<<<<<< HEAD
<<<<<<< Updated upstream
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb152-1"></a>paises_<span class="dv">2007</span> &lt;-<span class="st"> </span>readr<span class="op">::</span><span class="kw">read_csv</span>(<span class="st">&quot;datos/paises.csv&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb152-2"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb152-2"></a><span class="st">  </span><span class="kw">filter</span>(anio <span class="op">==</span><span class="st"> </span><span class="dv">2007</span>) </span>
<span id="cb152-3"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb152-3"></a></span>
<span id="cb152-4"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb152-4"></a>co2_<span class="dv">2007</span> &lt;-<span class="st"> </span>readr<span class="op">::</span><span class="kw">read_csv</span>(<span class="st">&quot;datos/co2_2007.csv&quot;</span>)</span>
<span id="cb152-5"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb152-5"></a>co2_<span class="dv">2007</span></span></code></pre></div>
=======
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb151-1" aria-hidden="true" tabindex="-1"></a>paises_2007 <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(<span class="st">&quot;datos/paises.csv&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb151-2"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb151-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(anio <span class="sc">==</span> <span class="dv">2007</span>) </span>
<span id="cb151-3"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb151-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb151-4"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb151-4" aria-hidden="true" tabindex="-1"></a>co2_2007 <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(<span class="st">&quot;datos/co2_2007.csv&quot;</span>)</span>
<span id="cb151-5"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb151-5" aria-hidden="true" tabindex="-1"></a>co2_2007</span></code></pre></div>
>>>>>>> Stashed changes
=======
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb116-1" aria-hidden="true" tabindex="-1"></a>paises_2007 <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(<span class="st">&quot;datos/paises.csv&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb116-2"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb116-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(anio <span class="sc">==</span> <span class="dv">2007</span>) </span>
<span id="cb116-3"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb116-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb116-4"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb116-4" aria-hidden="true" tabindex="-1"></a>co2_2007 <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(<span class="st">&quot;datos/co2_2007.csv&quot;</span>)</span>
<span id="cb116-5"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb116-5" aria-hidden="true" tabindex="-1"></a>co2_2007</span></code></pre></div>
>>>>>>> ggplot2
<pre><code>## # A tibble: 218 × 3
##    codigo_iso emision_co2 pais                  
##    &lt;chr&gt;            &lt;dbl&gt; &lt;chr&gt;                 
##  1 ABW            27.9    Aruba                 
##  2 AFG             0.0854 Afghanistán           
##  3 AGO             1.20   Angola                
##  4 ALB             1.32   Albania               
##  5 AND             6.52   Andorra               
##  6 ARB             4.10   Mundo Árabe           
##  7 ARE            22.4    Emiratos Árabes Unidos
##  8 ARG             4.38   Argentina             
##  9 ARM             1.73   Armenia               
## 10 ATG             5.14   Antigua y Barbuda     
## # … with 208 more rows</code></pre>
<p>Esta nueva tabla tiene 3 columnas: <code>codigo_iso</code> tiene el código ISO de 3 letras de (abreviaturas que se usan internacionalmente), <code>emision_co2</code> tiene las emisiones anuales per cápita de CO2 en toneladas, <code>pais</code> tiene el nombre del país.
Esta última columna también está presente en la tabla <code>paises_2007</code> y es la que va a servir como variable llave para unir las dos tablas.</p>
<p>Para unir las dos tablas, cualquier función <em>join</em> requiere cierta información:</p>
<ul>
<li>las tablas a unir: son los dos primeros argumentos.</li>
<li>qué variable o variables (se puede usar más de una!) usar para identificar coincidencias: el argumento <code>by</code>.</li>
</ul>
<p>Unamos <code>paises_2007</code> y <code>co2_2007</code> primero con <code>full_join()</code>:</p>
<<<<<<< HEAD
<<<<<<< Updated upstream
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb154-1"></a>paises_co2_<span class="dv">2007</span> &lt;-<span class="st"> </span><span class="kw">full_join</span>(paises_<span class="dv">2007</span>, co2_<span class="dv">2007</span>, <span class="dt">by =</span> <span class="st">&quot;pais&quot;</span>)</span>
<span id="cb154-2"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb154-2"></a>paises_co2_<span class="dv">2007</span></span></code></pre></div>
=======
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb153-1" aria-hidden="true" tabindex="-1"></a>paises_co2_2007 <span class="ot">&lt;-</span> <span class="fu">full_join</span>(paises_2007, co2_2007, <span class="at">by =</span> <span class="st">&quot;pais&quot;</span>)</span>
<span id="cb153-2"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb153-2" aria-hidden="true" tabindex="-1"></a>paises_co2_2007</span></code></pre></div>
>>>>>>> Stashed changes
=======
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb118-1" aria-hidden="true" tabindex="-1"></a>paises_co2_2007 <span class="ot">&lt;-</span> <span class="fu">full_join</span>(paises_2007, co2_2007, <span class="at">by =</span> <span class="st">&quot;pais&quot;</span>)</span>
<span id="cb118-2"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb118-2" aria-hidden="true" tabindex="-1"></a>paises_co2_2007</span></code></pre></div>
>>>>>>> ggplot2
<pre><code>## # A tibble: 241 × 8
##    pais       continente  anio esperanza_de_vi… poblacion pib_per_capita codigo_iso
##    &lt;chr&gt;      &lt;chr&gt;      &lt;dbl&gt;            &lt;dbl&gt;     &lt;dbl&gt;          &lt;dbl&gt; &lt;chr&gt;     
##  1 Afganistán Asia        2007             43.8  31889923           975. &lt;NA&gt;      
##  2 Albania    Europa      2007             76.4   3600523          5937. ALB       
##  3 Argelia    África      2007             72.3  33333216          6223. &lt;NA&gt;      
##  4 Angola     África      2007             42.7  12420476          4797. AGO       
##  5 Argentina  Américas    2007             75.3  40301927         12779. ARG       
##  6 Australia  Oceanía     2007             81.2  20434176         34435. AUS       
##  7 Austria    Europa      2007             79.8   8199783         36126. AUT       
##  8 Baréin     Asia        2007             75.6    708573         29796. &lt;NA&gt;      
##  9 Bangladesh Asia        2007             64.1 150448339          1391. BGD       
## 10 Bélgica    Europa      2007             79.4  10392226         33693. BEL       
## # … with 231 more rows, and 1 more variable: emision_co2 &lt;dbl&gt;</code></pre>
<p>Si miramos de cerca la tabla unida veremos un par de cosas:</p>
<ul>
<li>Todas las columnas de <code>paises_2007</code> y de <code>co2_2007</code> están presentes.</li>
<li>Todas las observaciones están presentes, aún los países que están presentes en <code>co2_2007</code> pero no en <code>paises_2007</code> y viceversa. En esos casos ahora tenemos <code>NA</code>. Esto genera una tabla con 241 filas.</li>
</ul>
<p>Esta es la opción más segura si no sabemos si todas las observaciones de una tabla están presente en a otra.</p>
<p>Si solo nos interesa conservar las filas de la tabla <em>de la izquierda</em>, en este caso <code>paises_2007</code> entonces:</p>
<<<<<<< HEAD
<<<<<<< Updated upstream
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb156-1"></a>paises_co2_<span class="dv">2007</span> &lt;-<span class="st"> </span><span class="kw">left_join</span>(paises_<span class="dv">2007</span>, co2_<span class="dv">2007</span>, <span class="dt">by =</span> <span class="st">&quot;pais&quot;</span>)</span>
<span id="cb156-2"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb156-2"></a>paises_co2_<span class="dv">2007</span></span></code></pre></div>
=======
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb155-1" aria-hidden="true" tabindex="-1"></a>paises_co2_2007 <span class="ot">&lt;-</span> <span class="fu">left_join</span>(paises_2007, co2_2007, <span class="at">by =</span> <span class="st">&quot;pais&quot;</span>)</span>
<span id="cb155-2"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb155-2" aria-hidden="true" tabindex="-1"></a>paises_co2_2007</span></code></pre></div>
>>>>>>> Stashed changes
=======
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb120-1" aria-hidden="true" tabindex="-1"></a>paises_co2_2007 <span class="ot">&lt;-</span> <span class="fu">left_join</span>(paises_2007, co2_2007, <span class="at">by =</span> <span class="st">&quot;pais&quot;</span>)</span>
<span id="cb120-2"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb120-2" aria-hidden="true" tabindex="-1"></a>paises_co2_2007</span></code></pre></div>
>>>>>>> ggplot2
<pre><code>## # A tibble: 142 × 8
##    pais       continente  anio esperanza_de_vi… poblacion pib_per_capita codigo_iso
##    &lt;chr&gt;      &lt;chr&gt;      &lt;dbl&gt;            &lt;dbl&gt;     &lt;dbl&gt;          &lt;dbl&gt; &lt;chr&gt;     
##  1 Afganistán Asia        2007             43.8  31889923           975. &lt;NA&gt;      
##  2 Albania    Europa      2007             76.4   3600523          5937. ALB       
##  3 Argelia    África      2007             72.3  33333216          6223. &lt;NA&gt;      
##  4 Angola     África      2007             42.7  12420476          4797. AGO       
##  5 Argentina  Américas    2007             75.3  40301927         12779. ARG       
##  6 Australia  Oceanía     2007             81.2  20434176         34435. AUS       
##  7 Austria    Europa      2007             79.8   8199783         36126. AUT       
##  8 Baréin     Asia        2007             75.6    708573         29796. &lt;NA&gt;      
##  9 Bangladesh Asia        2007             64.1 150448339          1391. BGD       
## 10 Bélgica    Europa      2007             79.4  10392226         33693. BEL       
## # … with 132 more rows, and 1 more variable: emision_co2 &lt;dbl&gt;</code></pre>
<p>Ahora esperamos que la tabla resultante tenga la misma cantidad de filas que <code>paises_2007</code> y efectivamente eso ocurre.
Pero al mismo tiempo varios países en esa tabla no encontraron coincidencia en <code>co2_2007</code> y por esa razón, la columna nueva columna <code>emisiones_co2</code> tiene <code>NA</code>.</p>
<p>Finalmente, si quisiéramos quedarnos solo con las observaciones que están presentes en ambas tablas usamos <code>inner_join()</code>.</p>
<<<<<<< HEAD
<<<<<<< Updated upstream
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb158-1"></a>paises_co2_<span class="dv">2007</span> &lt;-<span class="st"> </span><span class="kw">inner_join</span>(paises_<span class="dv">2007</span>, co2_<span class="dv">2007</span>, <span class="dt">by =</span> <span class="st">&quot;pais&quot;</span>)</span>
<span id="cb158-2"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb158-2"></a>paises_co2_<span class="dv">2007</span></span></code></pre></div>
=======
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb157-1" aria-hidden="true" tabindex="-1"></a>paises_co2_2007 <span class="ot">&lt;-</span> <span class="fu">inner_join</span>(paises_2007, co2_2007, <span class="at">by =</span> <span class="st">&quot;pais&quot;</span>)</span>
<span id="cb157-2"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb157-2" aria-hidden="true" tabindex="-1"></a>paises_co2_2007</span></code></pre></div>
>>>>>>> Stashed changes
=======
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb122-1" aria-hidden="true" tabindex="-1"></a>paises_co2_2007 <span class="ot">&lt;-</span> <span class="fu">inner_join</span>(paises_2007, co2_2007, <span class="at">by =</span> <span class="st">&quot;pais&quot;</span>)</span>
<span id="cb122-2"><a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii-1.html#cb122-2" aria-hidden="true" tabindex="-1"></a>paises_co2_2007</span></code></pre></div>
>>>>>>> ggplot2
<pre><code>## # A tibble: 119 × 8
##    pais    continente  anio esperanza_de_vi… poblacion pib_per_capita codigo_iso
##    &lt;chr&gt;   &lt;chr&gt;      &lt;dbl&gt;            &lt;dbl&gt;     &lt;dbl&gt;          &lt;dbl&gt; &lt;chr&gt;     
##  1 Albania Europa      2007             76.4   3600523          5937. ALB       
##  2 Angola  África      2007             42.7  12420476          4797. AGO       
##  3 Argent… Américas    2007             75.3  40301927         12779. ARG       
##  4 Austra… Oceanía     2007             81.2  20434176         34435. AUS       
##  5 Austria Europa      2007             79.8   8199783         36126. AUT       
##  6 Bangla… Asia        2007             64.1 150448339          1391. BGD       
##  7 Bélgica Europa      2007             79.4  10392226         33693. BEL       
##  8 Bolivia Américas    2007             65.6   9119152          3822. BOL       
##  9 Bosnia… Europa      2007             74.9   4552198          7446. BIH       
## 10 Botswa… África      2007             50.7   1639131         12570. BWA       
## # … with 109 more rows, and 1 more variable: emision_co2 &lt;dbl&gt;</code></pre>
<p>En este caso, perdemos las filas de <code>co2_2007</code> que no encontraron coincidencia en <code>paises_2007</code> y viceversa y la tabla resultante tiene aún menos filas (119).</p>
<div class="alert alert-info">
<p><strong>Desafío</strong></p>
<p>Estuvimos trabajando con una parte de la base de datos de emisiones.
Pero también está disponible <code>co2_completo.csv</code> que contiene las emisiones para distintos años.
El objetivo es que unas <code>paises</code> y <code>co2</code> teniendo en cuenta tanto el país como el año.
Para eso:</p>
<ol style="list-style-type: decimal">
<li>Lee la base de datos <code>co2_completo.csv</code> en una nueva variable que se llame <code>co2</code>.</li>
<li>Revisá el nombre de las variables en esta base de datos, ¿se llaman igual que las variables en <code>paises</code>?</li>
<li>Uní las dos tablas usando <code>full_join()</code>, tené en cuenta que ahora usamos dos variables llave <code>pais</code> y <code>anio</code>. Buscá en la documentación cómo indicarle eso a la función <code>full_join()</code>.<br />
</li>
</ol>
</div>

</div>
<<<<<<< HEAD
=======
<<<<<<< Updated upstream
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
>>>>>>> ggplot2
</div>
            </section>

          </div>
        </div>
      </div>
<<<<<<< HEAD
<a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="reportes-ii.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
=======
<<<<<<< Updated upstream
<<<<<<< Updated upstream
<a href="uniendo-tablas.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="de-ancho-a-largo-con-pivot-longer-1.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
=======
<a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="reportes-ii.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
>>>>>>> Stashed changes
=======
<a href="manipulación-de-datos-ordenados-usando-dplyr-y-tidyr-ii.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="reportes-ii.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
>>>>>>> Stashed changes
>>>>>>> ggplot2
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["DT6.pdf", "DT6.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
